/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Announcement):
<pre>{@code
string identifier

string name
string hostName
string reconnectKey
ModelFileDescription modelFileDescription

bool log
}</pre>
*/
public class Announcement implements ROS2Message<Announcement>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Announcement_";

   private final StringBuilder identifier_;
   private final StringBuilder name_;
   private final StringBuilder hostName_;
   private final StringBuilder reconnectKey_;
   private final logger_msgs.ModelFileDescription modelFileDescription_;
   private boolean log_;

   public Announcement()
   {
      identifier_ = new StringBuilder();
      name_ = new StringBuilder();
      hostName_ = new StringBuilder();
      reconnectKey_ = new StringBuilder();
      modelFileDescription_ = new logger_msgs.ModelFileDescription();
      log_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * identifier_.length()) + 1; // identifier_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * hostName_.length()) + 1; // hostName_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * reconnectKey_.length()) + 1; // reconnectKey_
      currentAlignment += modelFileDescription_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // log_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(identifier_);
      buffer.writeString(name_);
      buffer.writeString(hostName_);
      buffer.writeString(reconnectKey_);
      modelFileDescription_.serialize(buffer);
      buffer.writeBoolean(log_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(identifier_);
      buffer.readString(name_);
      buffer.readString(hostName_);
      buffer.readString(reconnectKey_);
      modelFileDescription_.deserialize(buffer);
      log_ = buffer.readBoolean();

   }

   @Override
   public void set(Announcement from)
   {
      identifier_.delete(0, identifier_.length());
      identifier_.insert(0, from.identifier_);
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      hostName_.delete(0, hostName_.length());
      hostName_.insert(0, from.hostName_);
      reconnectKey_.delete(0, reconnectKey_.length());
      reconnectKey_.insert(0, from.reconnectKey_);
      modelFileDescription_.set(from.modelFileDescription_);
      log_ = from.log_;

   }

   public StringBuilder getIdentifier()
   {
      return identifier_;
   }

   public java.lang.String getIdentifierAsString()
   {
      return identifier_.toString();
   }

   public void setIdentifier(java.lang.String s)
   {
      this.identifier_.delete(0, this.identifier_.length());
      this.identifier_.insert(0, s);
   }
   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }
   public StringBuilder getHostName()
   {
      return hostName_;
   }

   public java.lang.String getHostNameAsString()
   {
      return hostName_.toString();
   }

   public void setHostName(java.lang.String s)
   {
      this.hostName_.delete(0, this.hostName_.length());
      this.hostName_.insert(0, s);
   }
   public StringBuilder getReconnectKey()
   {
      return reconnectKey_;
   }

   public java.lang.String getReconnectKeyAsString()
   {
      return reconnectKey_.toString();
   }

   public void setReconnectKey(java.lang.String s)
   {
      this.reconnectKey_.delete(0, this.reconnectKey_.length());
      this.reconnectKey_.insert(0, s);
   }
   public logger_msgs.ModelFileDescription getModelFileDescription()
   {
      return modelFileDescription_;
   }

   public boolean getLog()
   {
      return log_;
   }

   public void setLog(boolean log_)
   {
      this.log_ = log_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Announcement {");
      builder.append("identifier_=");
      builder.append(identifier_.toString());
      builder.append("name_=");
      builder.append(name_.toString());
      builder.append("hostName_=");
      builder.append(hostName_.toString());
      builder.append("reconnectKey_=");
      builder.append(reconnectKey_.toString());
      builder.append("modelFileDescription_=");
      builder.append(modelFileDescription_);
      builder.append("log_=");
      builder.append(log_);

      builder.append("}");
      return builder.toString();
   }
}