/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/CameraType):
<pre>{@code
uint8 CAPTURE_CARD_MAGEWELL=0
uint8 CAPTURE_CARD=1
uint8 type 0
}</pre>
*/
public class CameraType implements ROS2Message<CameraType>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::CameraType_";

   public static final byte CAPTURE_CARD_MAGEWELL = 0;
   public static final byte CAPTURE_CARD = 1;
   private byte type_;

   public CameraType()
   {
      type_ = (byte) 0;

   }

   public CameraType(CameraType from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      type_ = buffer.readByte();

   }

   @Override
   public void set(CameraType from)
   {
      type_ = from.type_;

   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("CameraType {");
      builder.append("CAPTURE_CARD_MAGEWELL=");
      builder.append(CAPTURE_CARD_MAGEWELL);
      builder.append("CAPTURE_CARD=");
      builder.append(CAPTURE_CARD);
      builder.append("type_=");
      builder.append(type_);

      builder.append("}");
      return builder.toString();
   }
}