/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/ClearLogRequest):
<pre>{@code
string guid
}</pre>
*/
public class ClearLogRequest implements ROS2Message<ClearLogRequest>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::ClearLogRequest_";

   private final StringBuilder guid_;

   public ClearLogRequest()
   {
      guid_ = new StringBuilder();

   }

   public ClearLogRequest(ClearLogRequest from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * guid_.length()) + 1; // guid_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(guid_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(guid_);

   }

   @Override
   public void set(ClearLogRequest from)
   {
      guid_.delete(0, guid_.length());
      guid_.insert(0, from.guid_);

   }

   public StringBuilder getGuid()
   {
      return guid_;
   }

   public java.lang.String getGuidAsString()
   {
      return guid_.toString();
   }

   public void setGuid(java.lang.String s)
   {
      this.guid_.delete(0, this.guid_.length());
      this.guid_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ClearLogRequest {");
      builder.append("guid_=");
      builder.append(guid_.toString());

      builder.append("}");
      return builder.toString();
   }
}