/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/EnumType):
<pre>{@code
string name
string[] enumValues
}</pre>
*/
public class EnumType implements ROS2Message<EnumType>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::EnumType_";

   private final StringBuilder name_;
   private final IDLStringSequence enumValues_;

   public EnumType()
   {
      name_ = new StringBuilder();
      enumValues_ = new IDLStringSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += enumValues_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(name_);
      enumValues_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(name_);
      enumValues_.deserialize(buffer);

   }

   @Override
   public void set(EnumType from)
   {
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      enumValues_.set(from.enumValues_);

   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }
   public IDLStringSequence getEnumValues()
   {
      return enumValues_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("EnumType {");
      builder.append("name_=");
      builder.append(name_.toString());
      builder.append("enumValues_=");
      builder.append(enumValues_);

      builder.append("}");
      return builder.toString();
   }
}