/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/HandshakeFileType):
<pre>{@code
uint8 IDL_YAML=1
uint8 IDL_CDR=2
uint8 type 0}</pre>
*/
public class HandshakeFileType implements ROS2Message<HandshakeFileType>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::HandshakeFileType_";

   public static final byte IDL_YAML = 1;
   public static final byte IDL_CDR = 2;
   private byte type_;

   public HandshakeFileType()
   {
      type_ = (byte) 0;

   }

   public HandshakeFileType(HandshakeFileType from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      type_ = buffer.readByte();

   }

   @Override
   public void set(HandshakeFileType from)
   {
      type_ = from.type_;

   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("HandshakeFileType {");
      builder.append("IDL_YAML=");
      builder.append(IDL_YAML);
      builder.append("IDL_CDR=");
      builder.append(IDL_CDR);
      builder.append("type_=");
      builder.append(type_);

      builder.append("}");
      return builder.toString();
   }
}