/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Host):
<pre>{@code
string hostname
uint16 port
uint8[] cameras
}</pre>
*/
public class Host implements ROS2Message<Host>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Host_";

   private final StringBuilder hostname_;
   private int port_;
   private final IDLByteSequence cameras_;

   public Host()
   {
      hostname_ = new StringBuilder();
      cameras_ = new IDLByteSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * hostname_.length()) + 1; // hostname_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // port_
      currentAlignment += cameras_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(hostname_);
      buffer.writeUInt16(port_);
      cameras_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(hostname_);
      port_ = buffer.readUInt16();
      cameras_.deserialize(buffer);

   }

   @Override
   public void set(Host from)
   {
      hostname_.delete(0, hostname_.length());
      hostname_.insert(0, from.hostname_);
      port_ = from.port_;
      cameras_.set(from.cameras_);

   }

   public StringBuilder getHostname()
   {
      return hostname_;
   }

   public java.lang.String getHostnameAsString()
   {
      return hostname_.toString();
   }

   public void setHostname(java.lang.String s)
   {
      this.hostname_.delete(0, this.hostname_.length());
      this.hostname_.insert(0, s);
   }
   public int getPort()
   {
      return port_;
   }

   public void setPort(int port_)
   {
      this.port_ = port_;
   }

   public IDLByteSequence getCameras()
   {
      return cameras_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Host {");
      builder.append("hostname_=");
      builder.append(hostname_.toString());
      builder.append("port_=");
      builder.append(port_);
      builder.append("cameras_=");
      builder.append(cameras_);

      builder.append("}");
      return builder.toString();
   }
}