/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/ModelFileDescription):
<pre>{@code
bool hasModel
string name
string modelLoaderClass
string[] resourceDirectories

int32 modelFileSize

bool hasResourceZip
int32 resourceZipSize
}</pre>
*/
public class ModelFileDescription implements ROS2Message<ModelFileDescription>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::ModelFileDescription_";

   private boolean hasModel_;
   private final StringBuilder name_;
   private final StringBuilder modelLoaderClass_;
   private final IDLStringSequence resourceDirectories_;
   private int modelFileSize_;
   private boolean hasResourceZip_;
   private int resourceZipSize_;

   public ModelFileDescription()
   {
      hasModel_ = (boolean) false;
      name_ = new StringBuilder();
      modelLoaderClass_ = new StringBuilder();
      resourceDirectories_ = new IDLStringSequence();
      hasResourceZip_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // hasModel_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * modelLoaderClass_.length()) + 1; // modelLoaderClass_
      currentAlignment += resourceDirectories_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // modelFileSize_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // hasResourceZip_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // resourceZipSize_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(hasModel_);
      buffer.writeString(name_);
      buffer.writeString(modelLoaderClass_);
      resourceDirectories_.serialize(buffer);
      buffer.writeInt(modelFileSize_);
      buffer.writeBoolean(hasResourceZip_);
      buffer.writeInt(resourceZipSize_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      hasModel_ = buffer.readBoolean();
      buffer.readString(name_);
      buffer.readString(modelLoaderClass_);
      resourceDirectories_.deserialize(buffer);
      modelFileSize_ = buffer.readInt();
      hasResourceZip_ = buffer.readBoolean();
      resourceZipSize_ = buffer.readInt();

   }

   @Override
   public void set(ModelFileDescription from)
   {
      hasModel_ = from.hasModel_;
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      modelLoaderClass_.delete(0, modelLoaderClass_.length());
      modelLoaderClass_.insert(0, from.modelLoaderClass_);
      resourceDirectories_.set(from.resourceDirectories_);
      modelFileSize_ = from.modelFileSize_;
      hasResourceZip_ = from.hasResourceZip_;
      resourceZipSize_ = from.resourceZipSize_;

   }

   public boolean getHasModel()
   {
      return hasModel_;
   }

   public void setHasModel(boolean hasModel_)
   {
      this.hasModel_ = hasModel_;
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }
   public StringBuilder getModelLoaderClass()
   {
      return modelLoaderClass_;
   }

   public java.lang.String getModelLoaderClassAsString()
   {
      return modelLoaderClass_.toString();
   }

   public void setModelLoaderClass(java.lang.String s)
   {
      this.modelLoaderClass_.delete(0, this.modelLoaderClass_.length());
      this.modelLoaderClass_.insert(0, s);
   }
   public IDLStringSequence getResourceDirectories()
   {
      return resourceDirectories_;
   }

   public int getModelFileSize()
   {
      return modelFileSize_;
   }

   public void setModelFileSize(int modelFileSize_)
   {
      this.modelFileSize_ = modelFileSize_;
   }

   public boolean getHasResourceZip()
   {
      return hasResourceZip_;
   }

   public void setHasResourceZip(boolean hasResourceZip_)
   {
      this.hasResourceZip_ = hasResourceZip_;
   }

   public int getResourceZipSize()
   {
      return resourceZipSize_;
   }

   public void setResourceZipSize(int resourceZipSize_)
   {
      this.resourceZipSize_ = resourceZipSize_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ModelFileDescription {");
      builder.append("hasModel_=");
      builder.append(hasModel_);
      builder.append("name_=");
      builder.append(name_.toString());
      builder.append("modelLoaderClass_=");
      builder.append(modelLoaderClass_.toString());
      builder.append("resourceDirectories_=");
      builder.append(resourceDirectories_);
      builder.append("modelFileSize_=");
      builder.append(modelFileSize_);
      builder.append("hasResourceZip_=");
      builder.append(hasResourceZip_);
      builder.append("resourceZipSize_=");
      builder.append(resourceZipSize_);

      builder.append("}");
      return builder.toString();
   }
}