/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/ReferenceFrameInformation):
<pre>{@code
uint32[] frameIndices
string[] frameNames
}</pre>
*/
public class ReferenceFrameInformation implements ROS2Message<ReferenceFrameInformation>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::ReferenceFrameInformation_";

   private final IDLIntSequence frameIndices_;
   private final IDLStringSequence frameNames_;

   public ReferenceFrameInformation()
   {
      frameIndices_ = new IDLIntSequence();
      frameNames_ = new IDLStringSequence();

   }

   public ReferenceFrameInformation(ReferenceFrameInformation from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += frameIndices_.calculateSizeBytes(currentAlignment);
      currentAlignment += frameNames_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      frameIndices_.serialize(buffer);
      frameNames_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      frameIndices_.deserialize(buffer);
      frameNames_.deserialize(buffer);

   }

   @Override
   public void set(ReferenceFrameInformation from)
   {
      frameIndices_.set(from.frameIndices_);
      frameNames_.set(from.frameNames_);

   }

   public IDLIntSequence getFrameIndices()
   {
      return frameIndices_;
   }

   public IDLStringSequence getFrameNames()
   {
      return frameNames_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ReferenceFrameInformation {");
      builder.append("frameIndices_=");
      builder.append(frameIndices_);
      builder.append("frameNames_=");
      builder.append(frameNames_);

      builder.append("}");
      return builder.toString();
   }
}