/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/SCS1YoGraphicObjectMessage):
<pre>{@code
int32 registrationID
string name

uint16[1024] yoVariableIndex
float64[128] constants
SCS1AppearanceDefinitionMessage appearance
string listName
}</pre>
*/
public class SCS1YoGraphicObjectMessage implements ROS2Message<SCS1YoGraphicObjectMessage>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::SCS1YoGraphicObjectMessage_";

   private int registrationID_;
   private final StringBuilder name_;
   private final int[] yoVariableIndex_;
   private final double[] constants_;
   private final logger_msgs.SCS1AppearanceDefinitionMessage appearance_;
   private final StringBuilder listName_;

   public SCS1YoGraphicObjectMessage()
   {
      name_ = new StringBuilder();
      yoVariableIndex_ = new int[1024];
      constants_ = new double[128];
      appearance_ = new logger_msgs.SCS1AppearanceDefinitionMessage();
      listName_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // registrationID_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += (1024 * 2) + CDRBuffer.alignment(currentAlignment, (1024 * 2)); // yoVariableIndex_
      currentAlignment += (128 * 8) + CDRBuffer.alignment(currentAlignment, (128 * 8)); // constants_
      currentAlignment += appearance_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * listName_.length()) + 1; // listName_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(registrationID_);
      buffer.writeString(name_);
      for (int i = 0; i < yoVariableIndex_.length; ++i)
      {
         buffer.writeUInt16(yoVariableIndex_[i]);
      }
      for (int i = 0; i < constants_.length; ++i)
      {
         buffer.writeDouble(constants_[i]);
      }
      appearance_.serialize(buffer);
      buffer.writeString(listName_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      registrationID_ = buffer.readInt();
      buffer.readString(name_);
      for (int i = 0; i < yoVariableIndex_.length; ++i)
      {
         yoVariableIndex_[i] = buffer.readUInt16();
      }
      for (int i = 0; i < constants_.length; ++i)
      {
         constants_[i] = buffer.readDouble();
      }
      appearance_.deserialize(buffer);
      buffer.readString(listName_);

   }

   @Override
   public void set(SCS1YoGraphicObjectMessage from)
   {
      registrationID_ = from.registrationID_;
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      for (int i = 0; i < yoVariableIndex_.length; ++i)
      {
         yoVariableIndex_[i] = from.yoVariableIndex_[i];
      }
      for (int i = 0; i < constants_.length; ++i)
      {
         constants_[i] = from.constants_[i];
      }
      appearance_.set(from.appearance_);
      listName_.delete(0, listName_.length());
      listName_.insert(0, from.listName_);

   }

   public int getRegistrationID()
   {
      return registrationID_;
   }

   public void setRegistrationID(int registrationID_)
   {
      this.registrationID_ = registrationID_;
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }
   public int[] getYoVariableIndex()
   {
      return yoVariableIndex_;
   }

   public double[] getConstants()
   {
      return constants_;
   }

   public logger_msgs.SCS1AppearanceDefinitionMessage getAppearance()
   {
      return appearance_;
   }

   public StringBuilder getListName()
   {
      return listName_;
   }

   public java.lang.String getListNameAsString()
   {
      return listName_.toString();
   }

   public void setListName(java.lang.String s)
   {
      this.listName_.delete(0, this.listName_.length());
      this.listName_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SCS1YoGraphicObjectMessage {");
      builder.append("registrationID_=");
      builder.append(registrationID_);
      builder.append("name_=");
      builder.append(name_.toString());
      builder.append("yoVariableIndex_=");
      builder.append(java.util.Arrays.toString(yoVariableIndex_));
      builder.append("constants_=");
      builder.append(java.util.Arrays.toString(constants_));
      builder.append("appearance_=");
      builder.append(appearance_);
      builder.append("listName_=");
      builder.append(listName_.toString());

      builder.append("}");
      return builder.toString();
   }
}