/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/SCS2YoGraphicDefinitionMessage):
<pre>{@code
string[] fieldNames
string[] fieldValues
}</pre>
*/
public class SCS2YoGraphicDefinitionMessage implements ROS2Message<SCS2YoGraphicDefinitionMessage>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::SCS2YoGraphicDefinitionMessage_";

   private final IDLStringSequence fieldNames_;
   private final IDLStringSequence fieldValues_;

   public SCS2YoGraphicDefinitionMessage()
   {
      fieldNames_ = new IDLStringSequence();
      fieldValues_ = new IDLStringSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += fieldNames_.calculateSizeBytes(currentAlignment);
      currentAlignment += fieldValues_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      fieldNames_.serialize(buffer);
      fieldValues_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      fieldNames_.deserialize(buffer);
      fieldValues_.deserialize(buffer);

   }

   @Override
   public void set(SCS2YoGraphicDefinitionMessage from)
   {
      fieldNames_.set(from.fieldNames_);
      fieldValues_.set(from.fieldValues_);

   }

   public IDLStringSequence getFieldNames()
   {
      return fieldNames_;
   }

   public IDLStringSequence getFieldValues()
   {
      return fieldValues_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SCS2YoGraphicDefinitionMessage {");
      builder.append("fieldNames_=");
      builder.append(fieldNames_);
      builder.append("fieldValues_=");
      builder.append(fieldValues_);

      builder.append("}");
      return builder.toString();
   }
}