/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/StaticHostList):
<pre>{@code
bool disableAutoDiscovery
Host[] hosts
}</pre>
*/
public class StaticHostList implements ROS2Message<StaticHostList>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::StaticHostList_";

   private boolean disableAutoDiscovery_;
   private final IDLObjectSequence<logger_msgs.Host> hosts_;

   public StaticHostList()
   {
      disableAutoDiscovery_ = (boolean) false;
      hosts_ = new IDLObjectSequence<logger_msgs.Host>(logger_msgs.Host.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // disableAutoDiscovery_
      currentAlignment += hosts_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(disableAutoDiscovery_);
      hosts_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      disableAutoDiscovery_ = buffer.readBoolean();
      hosts_.deserialize(buffer);

   }

   @Override
   public void set(StaticHostList from)
   {
      disableAutoDiscovery_ = from.disableAutoDiscovery_;
      hosts_.set(from.hosts_);

   }

   public boolean getDisableAutoDiscovery()
   {
      return disableAutoDiscovery_;
   }

   public void setDisableAutoDiscovery(boolean disableAutoDiscovery_)
   {
      this.disableAutoDiscovery_ = disableAutoDiscovery_;
   }

   public IDLObjectSequence<logger_msgs.Host> getHosts()
   {
      return hosts_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("StaticHostList {");
      builder.append("disableAutoDiscovery_=");
      builder.append(disableAutoDiscovery_);
      builder.append("hosts_=");
      builder.append(hosts_);

      builder.append("}");
      return builder.toString();
   }
}