/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Summary):
<pre>{@code
bool createSummary
string summaryTriggerVariable
string[] summarizedVariables
}</pre>
*/
public class Summary implements ROS2Message<Summary>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Summary_";

   private boolean createSummary_;
   private final StringBuilder summaryTriggerVariable_;
   private final IDLStringSequence summarizedVariables_;

   public Summary()
   {
      createSummary_ = (boolean) false;
      summaryTriggerVariable_ = new StringBuilder();
      summarizedVariables_ = new IDLStringSequence();

   }

   public Summary(Summary from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // createSummary_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * summaryTriggerVariable_.length()) + 1; // summaryTriggerVariable_
      currentAlignment += summarizedVariables_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(createSummary_);
      buffer.writeString(summaryTriggerVariable_);
      summarizedVariables_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      createSummary_ = buffer.readBoolean();
      buffer.readString(summaryTriggerVariable_);
      summarizedVariables_.deserialize(buffer);

   }

   @Override
   public void set(Summary from)
   {
      createSummary_ = from.createSummary_;
      summaryTriggerVariable_.delete(0, summaryTriggerVariable_.length());
      summaryTriggerVariable_.insert(0, from.summaryTriggerVariable_);
      summarizedVariables_.set(from.summarizedVariables_);

   }

   public boolean getCreateSummary()
   {
      return createSummary_;
   }

   public void setCreateSummary(boolean createSummary_)
   {
      this.createSummary_ = createSummary_;
   }

   public StringBuilder getSummaryTriggerVariable()
   {
      return summaryTriggerVariable_;
   }

   public java.lang.String getSummaryTriggerVariableAsString()
   {
      return summaryTriggerVariable_.toString();
   }

   public void setSummaryTriggerVariable(java.lang.String s)
   {
      this.summaryTriggerVariable_.delete(0, this.summaryTriggerVariable_.length());
      this.summaryTriggerVariable_.insert(0, s);
   }
   public IDLStringSequence getSummarizedVariables()
   {
      return summarizedVariables_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Summary {");
      builder.append("createSummary_=");
      builder.append(createSummary_);
      builder.append("summaryTriggerVariable_=");
      builder.append(summaryTriggerVariable_.toString());
      builder.append("summarizedVariables_=");
      builder.append(summarizedVariables_);

      builder.append("}");
      return builder.toString();
   }
}