/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Synchronization):
<pre>{@code
float64 offset    # Index offset from the start of the parent log
float64 jogRate    # Jog rate compared to the parent log
}</pre>
*/
public class Synchronization implements ROS2Message<Synchronization>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Synchronization_";

   private double offset_; // Index offset from the start of the parent log
   private double jogRate_; // Jog rate compared to the parent log

   public Synchronization()
   {
   }

   public Synchronization(Synchronization from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // offset_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // jogRate_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(offset_);
      buffer.writeDouble(jogRate_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      offset_ = buffer.readDouble();
      jogRate_ = buffer.readDouble();

   }

   @Override
   public void set(Synchronization from)
   {
      offset_ = from.offset_;
      jogRate_ = from.jogRate_;

   }

   public double getOffset()
   {
      return offset_;
   }

   public void setOffset(double offset_)
   {
      this.offset_ = offset_;
   }

   public double getJogRate()
   {
      return jogRate_;
   }

   public void setJogRate(double jogRate_)
   {
      this.jogRate_ = jogRate_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Synchronization {");
      builder.append("offset_=");
      builder.append(offset_);
      builder.append("jogRate_=");
      builder.append(jogRate_);

      builder.append("}");
      return builder.toString();
   }
}