/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/VariableChangeRequest):
<pre>{@code
int32 variableID
float64 requestedValue
}</pre>
*/
public class VariableChangeRequest implements ROS2Message<VariableChangeRequest>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::VariableChangeRequest_";

   private int variableID_;
   private double requestedValue_;

   public VariableChangeRequest()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // variableID_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // requestedValue_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(variableID_);
      buffer.writeDouble(requestedValue_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      variableID_ = buffer.readInt();
      requestedValue_ = buffer.readDouble();

   }

   @Override
   public void set(VariableChangeRequest from)
   {
      variableID_ = from.variableID_;
      requestedValue_ = from.requestedValue_;

   }

   public int getVariableID()
   {
      return variableID_;
   }

   public void setVariableID(int variableID_)
   {
      this.variableID_ = variableID_;
   }

   public double getRequestedValue()
   {
      return requestedValue_;
   }

   public void setRequestedValue(double requestedValue_)
   {
      this.requestedValue_ = requestedValue_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("VariableChangeRequest {");
      builder.append("variableID_=");
      builder.append(variableID_);
      builder.append("requestedValue_=");
      builder.append(requestedValue_);

      builder.append("}");
      return builder.toString();
   }
}