/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Variables):
<pre>{@code
uint8 handshakeFileType
# Handshake file name
string handshake
# Data file name
string data
# Summary file name
string summary
# Variable index file
string index
# Does the index contain timestamps
bool timestamped
# Is the data compressed
bool compressed
# Number of ticks per compressed block; 0 or 1 means per-tick (legacy)
int64 compressionBatchSize
# Number of valid ticks in the last compressed block; 0 means all ticks are valid (legacy)
int64 validTicksInLastBatch
# Compression codec used: "zstd" or empty/absent means snappy (legacy)
string compressionType
}</pre>
*/
public class Variables implements ROS2Message<Variables>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Variables_";

   private byte handshakeFileType_;
   /**
      Handshake file name
   */
   private final StringBuilder handshake_;
   /**
      Data file name
   */
   private final StringBuilder data_;
   /**
      Summary file name
   */
   private final StringBuilder summary_;
   /**
      Variable index file
   */
   private final StringBuilder index_;
   /**
      Does the index contain timestamps
   */
   private boolean timestamped_;
   /**
      Is the data compressed
   */
   private boolean compressed_;
   /**
      Number of ticks per compressed block; 0 or 1 means per-tick (legacy)
   */
   private long compressionBatchSize_;
   /**
      Number of valid ticks in the last compressed block; 0 means all ticks are valid (legacy)
   */
   private long validTicksInLastBatch_;
   /**
      Compression codec used: "zstd" or empty/absent means snappy (legacy)
   */
   private final StringBuilder compressionType_;

   public Variables()
   {
      handshake_ = new StringBuilder();
      data_ = new StringBuilder();
      summary_ = new StringBuilder();
      index_ = new StringBuilder();
      timestamped_ = (boolean) false;
      compressed_ = (boolean) false;
      compressionType_ = new StringBuilder();

   }

   public Variables(Variables from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // handshakeFileType_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * handshake_.length()) + 1; // handshake_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * data_.length()) + 1; // data_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * summary_.length()) + 1; // summary_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * index_.length()) + 1; // index_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // timestamped_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // compressed_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // compressionBatchSize_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // validTicksInLastBatch_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * compressionType_.length()) + 1; // compressionType_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(handshakeFileType_);
      buffer.writeString(handshake_);
      buffer.writeString(data_);
      buffer.writeString(summary_);
      buffer.writeString(index_);
      buffer.writeBoolean(timestamped_);
      buffer.writeBoolean(compressed_);
      buffer.writeLong(compressionBatchSize_);
      buffer.writeLong(validTicksInLastBatch_);
      buffer.writeString(compressionType_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      handshakeFileType_ = buffer.readByte();
      buffer.readString(handshake_);
      buffer.readString(data_);
      buffer.readString(summary_);
      buffer.readString(index_);
      timestamped_ = buffer.readBoolean();
      compressed_ = buffer.readBoolean();
      compressionBatchSize_ = buffer.readLong();
      validTicksInLastBatch_ = buffer.readLong();
      buffer.readString(compressionType_);

   }

   @Override
   public void set(Variables from)
   {
      handshakeFileType_ = from.handshakeFileType_;
      handshake_.delete(0, handshake_.length());
      handshake_.insert(0, from.handshake_);
      data_.delete(0, data_.length());
      data_.insert(0, from.data_);
      summary_.delete(0, summary_.length());
      summary_.insert(0, from.summary_);
      index_.delete(0, index_.length());
      index_.insert(0, from.index_);
      timestamped_ = from.timestamped_;
      compressed_ = from.compressed_;
      compressionBatchSize_ = from.compressionBatchSize_;
      validTicksInLastBatch_ = from.validTicksInLastBatch_;
      compressionType_.delete(0, compressionType_.length());
      compressionType_.insert(0, from.compressionType_);

   }

   public byte getHandshakeFileType()
   {
      return handshakeFileType_;
   }

   public void setHandshakeFileType(byte handshakeFileType_)
   {
      this.handshakeFileType_ = handshakeFileType_;
   }

   public StringBuilder getHandshake()
   {
      return handshake_;
   }

   public java.lang.String getHandshakeAsString()
   {
      return handshake_.toString();
   }

   public void setHandshake(java.lang.String s)
   {
      this.handshake_.delete(0, this.handshake_.length());
      this.handshake_.insert(0, s);
   }
   public StringBuilder getData()
   {
      return data_;
   }

   public java.lang.String getDataAsString()
   {
      return data_.toString();
   }

   public void setData(java.lang.String s)
   {
      this.data_.delete(0, this.data_.length());
      this.data_.insert(0, s);
   }
   public StringBuilder getSummary()
   {
      return summary_;
   }

   public java.lang.String getSummaryAsString()
   {
      return summary_.toString();
   }

   public void setSummary(java.lang.String s)
   {
      this.summary_.delete(0, this.summary_.length());
      this.summary_.insert(0, s);
   }
   public StringBuilder getIndex()
   {
      return index_;
   }

   public java.lang.String getIndexAsString()
   {
      return index_.toString();
   }

   public void setIndex(java.lang.String s)
   {
      this.index_.delete(0, this.index_.length());
      this.index_.insert(0, s);
   }
   public boolean getTimestamped()
   {
      return timestamped_;
   }

   public void setTimestamped(boolean timestamped_)
   {
      this.timestamped_ = timestamped_;
   }

   public boolean getCompressed()
   {
      return compressed_;
   }

   public void setCompressed(boolean compressed_)
   {
      this.compressed_ = compressed_;
   }

   public long getCompressionBatchSize()
   {
      return compressionBatchSize_;
   }

   public void setCompressionBatchSize(long compressionBatchSize_)
   {
      this.compressionBatchSize_ = compressionBatchSize_;
   }

   public long getValidTicksInLastBatch()
   {
      return validTicksInLastBatch_;
   }

   public void setValidTicksInLastBatch(long validTicksInLastBatch_)
   {
      this.validTicksInLastBatch_ = validTicksInLastBatch_;
   }

   public StringBuilder getCompressionType()
   {
      return compressionType_;
   }

   public java.lang.String getCompressionTypeAsString()
   {
      return compressionType_.toString();
   }

   public void setCompressionType(java.lang.String s)
   {
      this.compressionType_.delete(0, this.compressionType_.length());
      this.compressionType_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Variables {");
      builder.append("handshakeFileType_=");
      builder.append(handshakeFileType_);
      builder.append("handshake_=");
      builder.append(handshake_.toString());
      builder.append("data_=");
      builder.append(data_.toString());
      builder.append("summary_=");
      builder.append(summary_.toString());
      builder.append("index_=");
      builder.append(index_.toString());
      builder.append("timestamped_=");
      builder.append(timestamped_);
      builder.append("compressed_=");
      builder.append(compressed_);
      builder.append("compressionBatchSize_=");
      builder.append(compressionBatchSize_);
      builder.append("validTicksInLastBatch_=");
      builder.append(validTicksInLastBatch_);
      builder.append("compressionType_=");
      builder.append(compressionType_.toString());

      builder.append("}");
      return builder.toString();
   }
}