/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/YoRegistryDefinition):
<pre>{@code
uint16 parent
string name
}</pre>
*/
public class YoRegistryDefinition implements ROS2Message<YoRegistryDefinition>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::YoRegistryDefinition_";

   private int parent_;
   private final StringBuilder name_;

   public YoRegistryDefinition()
   {
      name_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // parent_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeUInt16(parent_);
      buffer.writeString(name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      parent_ = buffer.readUInt16();
      buffer.readString(name_);

   }

   @Override
   public void set(YoRegistryDefinition from)
   {
      parent_ = from.parent_;
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);

   }

   public int getParent()
   {
      return parent_;
   }

   public void setParent(int parent_)
   {
      this.parent_ = parent_;
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("YoRegistryDefinition {");
      builder.append("parent_=");
      builder.append(parent_);
      builder.append("name_=");
      builder.append(name_.toString());

      builder.append("}");
      return builder.toString();
   }
}