/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/YoType):
<pre>{@code
uint8 DoubleYoVariable=0
uint8 BooleanYoVariable=1
uint8 IntegerYoVariable=2
uint8 LongYoVariable=3
uint8 EnumYoVariable=4
uint8 type 0}</pre>
*/
public class YoType implements ROS2Message<YoType>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::YoType_";

   public static final byte DOUBLEYOVARIABLE = 0;
   public static final byte BOOLEANYOVARIABLE = 1;
   public static final byte INTEGERYOVARIABLE = 2;
   public static final byte LONGYOVARIABLE = 3;
   public static final byte ENUMYOVARIABLE = 4;
   private byte type_;

   public YoType()
   {
      type_ = (byte) 0;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      type_ = buffer.readByte();

   }

   @Override
   public void set(YoType from)
   {
      type_ = from.type_;

   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("YoType {");
      builder.append("DOUBLEYOVARIABLE=");
      builder.append(DOUBLEYOVARIABLE);
      builder.append("BOOLEANYOVARIABLE=");
      builder.append(BOOLEANYOVARIABLE);
      builder.append("INTEGERYOVARIABLE=");
      builder.append(INTEGERYOVARIABLE);
      builder.append("LONGYOVARIABLE=");
      builder.append(LONGYOVARIABLE);
      builder.append("ENUMYOVARIABLE=");
      builder.append(ENUMYOVARIABLE);
      builder.append("type_=");
      builder.append(type_);

      builder.append("}");
      return builder.toString();
   }
}