/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/ZEDSDKAnnounce):
<pre>{@code
string sensor_name
int32 depthMode
string address
int16 port
int32 fps
int32 bitrate
int64 sensorTimestamp
int64 controllerTimestamp
}</pre>
*/
public class ZEDSDKAnnounce implements ROS2Message<ZEDSDKAnnounce>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::ZEDSDKAnnounce_";

   private final StringBuilder sensor_name_;
   private int depthMode_;
   private final StringBuilder address_;
   private short port_;
   private int fps_;
   private int bitrate_;
   private long sensorTimestamp_;
   private long controllerTimestamp_;

   public ZEDSDKAnnounce()
   {
      sensor_name_ = new StringBuilder();
      address_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * sensor_name_.length()) + 1; // sensor_name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // depthMode_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * address_.length()) + 1; // address_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // port_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // fps_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // bitrate_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sensorTimestamp_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // controllerTimestamp_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(sensor_name_);
      buffer.writeInt(depthMode_);
      buffer.writeString(address_);
      buffer.writeShort(port_);
      buffer.writeInt(fps_);
      buffer.writeInt(bitrate_);
      buffer.writeLong(sensorTimestamp_);
      buffer.writeLong(controllerTimestamp_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(sensor_name_);
      depthMode_ = buffer.readInt();
      buffer.readString(address_);
      port_ = buffer.readShort();
      fps_ = buffer.readInt();
      bitrate_ = buffer.readInt();
      sensorTimestamp_ = buffer.readLong();
      controllerTimestamp_ = buffer.readLong();

   }

   @Override
   public void set(ZEDSDKAnnounce from)
   {
      sensor_name_.delete(0, sensor_name_.length());
      sensor_name_.insert(0, from.sensor_name_);
      depthMode_ = from.depthMode_;
      address_.delete(0, address_.length());
      address_.insert(0, from.address_);
      port_ = from.port_;
      fps_ = from.fps_;
      bitrate_ = from.bitrate_;
      sensorTimestamp_ = from.sensorTimestamp_;
      controllerTimestamp_ = from.controllerTimestamp_;

   }

   public StringBuilder getSensorName()
   {
      return sensor_name_;
   }

   public java.lang.String getSensorNameAsString()
   {
      return sensor_name_.toString();
   }

   public void setSensorName(java.lang.String s)
   {
      this.sensor_name_.delete(0, this.sensor_name_.length());
      this.sensor_name_.insert(0, s);
   }
   public int getDepthMode()
   {
      return depthMode_;
   }

   public void setDepthMode(int depthMode_)
   {
      this.depthMode_ = depthMode_;
   }

   public StringBuilder getAddress()
   {
      return address_;
   }

   public java.lang.String getAddressAsString()
   {
      return address_.toString();
   }

   public void setAddress(java.lang.String s)
   {
      this.address_.delete(0, this.address_.length());
      this.address_.insert(0, s);
   }
   public short getPort()
   {
      return port_;
   }

   public void setPort(short port_)
   {
      this.port_ = port_;
   }

   public int getFps()
   {
      return fps_;
   }

   public void setFps(int fps_)
   {
      this.fps_ = fps_;
   }

   public int getBitrate()
   {
      return bitrate_;
   }

   public void setBitrate(int bitrate_)
   {
      this.bitrate_ = bitrate_;
   }

   public long getSensorTimestamp()
   {
      return sensorTimestamp_;
   }

   public void setSensorTimestamp(long sensorTimestamp_)
   {
      this.sensorTimestamp_ = sensorTimestamp_;
   }

   public long getControllerTimestamp()
   {
      return controllerTimestamp_;
   }

   public void setControllerTimestamp(long controllerTimestamp_)
   {
      this.controllerTimestamp_ = controllerTimestamp_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ZEDSDKAnnounce {");
      builder.append("sensor_name_=");
      builder.append(sensor_name_.toString());
      builder.append("depthMode_=");
      builder.append(depthMode_);
      builder.append("address_=");
      builder.append(address_.toString());
      builder.append("port_=");
      builder.append(port_);
      builder.append("fps_=");
      builder.append(fps_);
      builder.append("bitrate_=");
      builder.append(bitrate_);
      builder.append("sensorTimestamp_=");
      builder.append(sensorTimestamp_);
      builder.append("controllerTimestamp_=");
      builder.append(controllerTimestamp_);

      builder.append("}");
      return builder.toString();
   }
}