/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/HeightScanMessage):
<pre>{@code
# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Controller timestamp to sync playback in the log, nanoseconds.
int64 controllerTimestamp

# Frame of reference
string frame_id

# Origin of the grid's corner relative to frame of reference; grid is positioned in the x-y
# plane relative to this origin
geometry_msgs/Pose pose

# Number of grid columns
uint32 column_count

# Size of a single grid cell along the x and y axes, relative to `pose`
Vector2 cell_size

# Number of bytes between rows in `data`
uint32 row_stride

# Number of bytes between cells within a row in `data`
uint32 cell_stride

# Fields in `data`
PackedElementField[] fields

# Grid cell data, interpreted using `fields`, in row-major (y-major) order
uint8[] data
}</pre>
*/
public class HeightScanMessage implements ROS2Message<HeightScanMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::HeightScanMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Controller timestamp to sync playback in the log, nanoseconds.
   */
   private long controllerTimestamp_;
   /**
      Frame of reference
   */
   private final StringBuilder frame_id_;
   /**
      Origin of the grid's corner relative to frame of reference; grid is positioned in the x-y
      plane relative to this origin
   */
   private final geometry_msgs.Pose pose_;
   /**
      Number of grid columns
   */
   private int column_count_;
   /**
      Size of a single grid cell along the x and y axes, relative to `pose`
   */
   private final perception_msgs.Vector2 cell_size_;
   /**
      Number of bytes between rows in `data`
   */
   private int row_stride_;
   /**
      Number of bytes between cells within a row in `data`
   */
   private int cell_stride_;
   /**
      Fields in `data`
   */
   private final IDLObjectSequence<perception_msgs.PackedElementField> fields_;
   /**
      Grid cell data, interpreted using `fields`, in row-major (y-major) order
   */
   private final IDLByteSequence data_;

   public HeightScanMessage()
   {
      frame_id_ = new StringBuilder();
      pose_ = new geometry_msgs.Pose();
      cell_size_ = new perception_msgs.Vector2();
      fields_ = new IDLObjectSequence<perception_msgs.PackedElementField>(perception_msgs.PackedElementField.class);
      data_ = new IDLByteSequence();

   }

   public HeightScanMessage(HeightScanMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // controllerTimestamp_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * frame_id_.length()) + 1; // frame_id_
      currentAlignment += pose_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // column_count_
      currentAlignment += cell_size_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // row_stride_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // cell_stride_
      currentAlignment += fields_.calculateSizeBytes(currentAlignment);
      currentAlignment += data_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeLong(controllerTimestamp_);
      buffer.writeString(frame_id_);
      pose_.serialize(buffer);
      buffer.writeInt(column_count_);
      cell_size_.serialize(buffer);
      buffer.writeInt(row_stride_);
      buffer.writeInt(cell_stride_);
      fields_.serialize(buffer);
      data_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      controllerTimestamp_ = buffer.readLong();
      buffer.readString(frame_id_);
      pose_.deserialize(buffer);
      column_count_ = buffer.readInt();
      cell_size_.deserialize(buffer);
      row_stride_ = buffer.readInt();
      cell_stride_ = buffer.readInt();
      fields_.deserialize(buffer);
      data_.deserialize(buffer);

   }

   @Override
   public void set(HeightScanMessage from)
   {
      sequence_id_ = from.sequence_id_;
      controllerTimestamp_ = from.controllerTimestamp_;
      frame_id_.delete(0, frame_id_.length());
      frame_id_.insert(0, from.frame_id_);
      pose_.set(from.pose_);
      column_count_ = from.column_count_;
      cell_size_.set(from.cell_size_);
      row_stride_ = from.row_stride_;
      cell_stride_ = from.cell_stride_;
      fields_.set(from.fields_);
      data_.set(from.data_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public long getControllerTimestamp()
   {
      return controllerTimestamp_;
   }

   public void setControllerTimestamp(long controllerTimestamp_)
   {
      this.controllerTimestamp_ = controllerTimestamp_;
   }

   public StringBuilder getFrameId()
   {
      return frame_id_;
   }

   public java.lang.String getFrameIdAsString()
   {
      return frame_id_.toString();
   }

   public void setFrameId(java.lang.String s)
   {
      this.frame_id_.delete(0, this.frame_id_.length());
      this.frame_id_.insert(0, s);
   }
   public geometry_msgs.Pose getPose()
   {
      return pose_;
   }

   public int getColumnCount()
   {
      return column_count_;
   }

   public void setColumnCount(int column_count_)
   {
      this.column_count_ = column_count_;
   }

   public perception_msgs.Vector2 getCellSize()
   {
      return cell_size_;
   }

   public int getRowStride()
   {
      return row_stride_;
   }

   public void setRowStride(int row_stride_)
   {
      this.row_stride_ = row_stride_;
   }

   public int getCellStride()
   {
      return cell_stride_;
   }

   public void setCellStride(int cell_stride_)
   {
      this.cell_stride_ = cell_stride_;
   }

   public IDLObjectSequence<perception_msgs.PackedElementField> getFields()
   {
      return fields_;
   }

   public IDLByteSequence getData()
   {
      return data_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("HeightScanMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("controllerTimestamp_=");
      builder.append(controllerTimestamp_);
      builder.append("frame_id_=");
      builder.append(frame_id_.toString());
      builder.append("pose_=");
      builder.append(pose_);
      builder.append("column_count_=");
      builder.append(column_count_);
      builder.append("cell_size_=");
      builder.append(cell_size_);
      builder.append("row_stride_=");
      builder.append(row_stride_);
      builder.append("cell_stride_=");
      builder.append(cell_stride_);
      builder.append("fields_=");
      builder.append(fields_);
      builder.append("data_=");
      builder.append(data_);

      builder.append("}");
      return builder.toString();
   }
}