/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A field present within each element in a byte array of packed elements.
Field layout matches Foxglove's foxglove_msgs/msg/PackedElementField so this can be used
in the `fields` array of a Grid message that Foxglove's 3D panel will recognize natively.
<p>Source (perception_msgs/PackedElementField):
<pre>{@code
# A field present within each element in a byte array of packed elements.
# Field layout matches Foxglove's foxglove_msgs/msg/PackedElementField so this can be used
# in the `fields` array of a Grid message that Foxglove's 3D panel will recognize natively.

# Name of the field
string name

# Byte offset from start of data buffer
uint32 offset

# Unknown numeric type
uint8 UNKNOWN = 0

# Unsigned 8-bit integer
uint8 UINT8 = 1

# Signed 8-bit integer
uint8 INT8 = 2

# Unsigned 16-bit integer
uint8 UINT16 = 3

# Signed 16-bit integer
uint8 INT16 = 4

# Unsigned 32-bit integer
uint8 UINT32 = 5

# Signed 32-bit integer
uint8 INT32 = 6

# 32-bit floating-point number
uint8 FLOAT32 = 7

# 64-bit floating-point number
uint8 FLOAT64 = 8

# Type of data in the field. Integers are stored using little-endian byte order.
uint8 type
}</pre>
*/
public class PackedElementField implements ROS2Message<PackedElementField>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::PackedElementField_";

   /**
      Name of the field
   */
   private final StringBuilder name_;
   /**
      Byte offset from start of data buffer
   */
   private int offset_;
   /**
      Unknown numeric type
   */
   public static final byte UNKNOWN = 0;
   /**
      Unsigned 8-bit integer
   */
   public static final byte UINT8 = 1;
   /**
      Signed 8-bit integer
   */
   public static final byte INT8 = 2;
   /**
      Unsigned 16-bit integer
   */
   public static final byte UINT16 = 3;
   /**
      Signed 16-bit integer
   */
   public static final byte INT16 = 4;
   /**
      Unsigned 32-bit integer
   */
   public static final byte UINT32 = 5;
   /**
      Signed 32-bit integer
   */
   public static final byte INT32 = 6;
   /**
      32-bit floating-point number
   */
   public static final byte FLOAT32 = 7;
   /**
      64-bit floating-point number
   */
   public static final byte FLOAT64 = 8;
   /**
      Type of data in the field. Integers are stored using little-endian byte order.
   */
   private byte type_;

   public PackedElementField()
   {
      name_ = new StringBuilder();

   }

   public PackedElementField(PackedElementField from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // offset_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(name_);
      buffer.writeInt(offset_);
      buffer.writeByte(type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(name_);
      offset_ = buffer.readInt();
      type_ = buffer.readByte();

   }

   @Override
   public void set(PackedElementField from)
   {
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      offset_ = from.offset_;
      type_ = from.type_;

   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }
   public int getOffset()
   {
      return offset_;
   }

   public void setOffset(int offset_)
   {
      this.offset_ = offset_;
   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("PackedElementField {");
      builder.append("name_=");
      builder.append(name_.toString());
      builder.append("offset_=");
      builder.append(offset_);
      builder.append("UNKNOWN=");
      builder.append(UNKNOWN);
      builder.append("UINT8=");
      builder.append(UINT8);
      builder.append("INT8=");
      builder.append(INT8);
      builder.append("UINT16=");
      builder.append(UINT16);
      builder.append("INT16=");
      builder.append(INT16);
      builder.append("UINT32=");
      builder.append(UINT32);
      builder.append("INT32=");
      builder.append(INT32);
      builder.append("FLOAT32=");
      builder.append(FLOAT32);
      builder.append("FLOAT64=");
      builder.append(FLOAT64);
      builder.append("type_=");
      builder.append(type_);

      builder.append("}");
      return builder.toString();
   }
}