/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A vector in 2D space that represents a direction only.
Field layout matches Foxglove's foxglove_msgs/msg/Vector2 so this can be used as the
cell_size of a Grid message that Foxglove's 3D panel will recognize natively.
<p>Source (perception_msgs/Vector2):
<pre>{@code
# A vector in 2D space that represents a direction only.
# Field layout matches Foxglove's foxglove_msgs/msg/Vector2 so this can be used as the
# cell_size of a Grid message that Foxglove's 3D panel will recognize natively.

# x component
float64 x

# y component
float64 y
}</pre>
*/
public class Vector2 implements ROS2Message<Vector2>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::Vector2_";

   /**
      x component
   */
   private double x_;
   /**
      y component
   */
   private double y_;

   public Vector2()
   {
   }

   public Vector2(Vector2 from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // x_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // y_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(x_);
      buffer.writeDouble(y_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      x_ = buffer.readDouble();
      y_ = buffer.readDouble();

   }

   @Override
   public void set(Vector2 from)
   {
      x_ = from.x_;
      y_ = from.y_;

   }

   public double getX()
   {
      return x_;
   }

   public void setX(double x_)
   {
      this.x_ = x_;
   }

   public double getY()
   {
      return y_;
   }

   public void setY(double y_)
   {
      this.y_ = y_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Vector2 {");
      builder.append("x_=");
      builder.append(x_);
      builder.append("y_=");
      builder.append(y_);

      builder.append("}");
      return builder.toString();
   }
}