module us{
module ihmc{
module robotDataLogger{

	
	struct ModelFileDescription{
		boolean hasModel;
		string name;
		string modelLoaderClass;
		sequence<string, 255> resourceDirectories;
		
		long modelFileSize;
		
		boolean hasResourceZip;
		long resourceZipSize;
	};
		
		
	struct Announcement
	{
		string identifier;
		
		string name;
		string hostName;
		string reconnectKey;
		ModelFileDescription modelFileDescription;
		
		boolean log;
	};
};
};
};