module us{
module ihmc{
module robotDataLogger{


	struct Host
	{
		string hostname;
		unsigned short port;
		sequence<octet, 128> cameras;
	};
	
	struct StaticHostList
	{
		boolean disableAutoDiscovery;
		sequence<Host, 128> hosts;
	};

};
};
};