module us{
module ihmc{
module robotDataLogger{
	struct ZEDSDKAnnounce{
		string sensor_name;
		int depth_mode;
		string address;
		short port;
		long fps;
		long bitrate;
		long long sensorTimestamp;
		long long controllerTimestamp;
	};
};
};
};