/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Camera):
<pre>{@code
# Camera definition
string type    # Type of capture method used
string name    # Human readable camera name
bool interlaced    # Is the input interlaced
string videoFile    # Video file
string timestampFile    # Timestamps for video file
}</pre>
*/
public class Camera implements ROS2Message<Camera>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::Camera";

   /**
      Camera definition
   */
   private final StringBuilder type_; // Type of capture method used
   private final StringBuilder name_; // Human readable camera name
   private boolean interlaced_; // Is the input interlaced
   private final StringBuilder videoFile_; // Video file
   private final StringBuilder timestampFile_; // Timestamps for video file

   public Camera()
   {
      type_ = new StringBuilder();
      name_ = new StringBuilder();
      interlaced_ = (boolean) false;
      videoFile_ = new StringBuilder();
      timestampFile_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * type_.length()) + 1; // type_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // interlaced_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * videoFile_.length()) + 1; // videoFile_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * timestampFile_.length()) + 1; // timestampFile_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(type_);
      buffer.writeString(name_);
      buffer.writeBoolean(interlaced_);
      buffer.writeString(videoFile_);
      buffer.writeString(timestampFile_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(type_);
      buffer.readString(name_);
      interlaced_ = buffer.readBoolean();
      buffer.readString(videoFile_);
      buffer.readString(timestampFile_);

   }

   @Override
   public void set(Camera from)
   {
      type_.delete(0, type_.length());
      type_.insert(0, from.type_);
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      interlaced_ = from.interlaced_;
      videoFile_.delete(0, videoFile_.length());
      videoFile_.insert(0, from.videoFile_);
      timestampFile_.delete(0, timestampFile_.length());
      timestampFile_.insert(0, from.timestampFile_);

   }

   public StringBuilder getType()
   {
      return type_;
   }

   public java.lang.String getTypeAsString()
   {
      return type_.toString();
   }

   public void setType(java.lang.String s)
   {
      this.type_.delete(0, this.type_.length());
      this.type_.insert(0, s);
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   public boolean getInterlaced()
   {
      return interlaced_;
   }

   public void setInterlaced(boolean interlaced_)
   {
      this.interlaced_ = interlaced_;
   }

   public StringBuilder getVideoFile()
   {
      return videoFile_;
   }

   public java.lang.String getVideoFileAsString()
   {
      return videoFile_.toString();
   }

   public void setVideoFile(java.lang.String s)
   {
      this.videoFile_.delete(0, this.videoFile_.length());
      this.videoFile_.insert(0, s);
   }

   public StringBuilder getTimestampFile()
   {
      return timestampFile_;
   }

   public java.lang.String getTimestampFileAsString()
   {
      return timestampFile_.toString();
   }

   public void setTimestampFile(java.lang.String s)
   {
      this.timestampFile_.delete(0, this.timestampFile_.length());
      this.timestampFile_.insert(0, s);
   }


}