/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/CameraSettings):
<pre>{@code
CameraConfiguration[128] cameras
}</pre>
*/
public class CameraSettings implements ROS2Message<CameraSettings>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::CameraSettings_";

   private final logger_msgs.msg.dds.CameraConfiguration[] cameras_;

   public CameraSettings()
   {
      cameras_ = new logger_msgs.msg.dds.CameraConfiguration[128];
      // cameras is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < cameras_.length; ++i)
      {
         cameras_[i] = new logger_msgs.msg.dds.CameraConfiguration();
      }

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      for (int i = 0; i < cameras_.length; ++i)
      {
         currentAlignment += cameras_[i].calculateSizeBytes(currentAlignment);
      }

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      for (int i = 0; i < cameras_.length; ++i)
      {
         cameras_[i].serialize(buffer);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      for (int i = 0; i < cameras_.length; ++i)
      {
         cameras_[i].deserialize(buffer);
      }

   }

   @Override
   public void set(CameraSettings from)
   {
      for (int i = 0; i < cameras_.length; ++i)
      {
         cameras_[i].set(from.cameras_[i]);
      }

   }

   public logger_msgs.msg.dds.CameraConfiguration[] getCameras()
   {
      return cameras_;
   }


}