/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/CameraSettings):
<pre>{@code
CameraConfiguration[] cameras
}</pre>
*/
public class CameraSettings implements ROS2Message<CameraSettings>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::CameraSettings";

   private final IDLObjectSequence<logger_msgs.msg.dds.CameraConfiguration> cameras_;

   public CameraSettings()
   {
      cameras_ = new IDLObjectSequence<logger_msgs.msg.dds.CameraConfiguration>(logger_msgs.msg.dds.CameraConfiguration.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += cameras_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      cameras_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      cameras_.deserialize(buffer);

   }

   @Override
   public void set(CameraSettings from)
   {
      cameras_.set(from.cameras_);

   }

   public IDLObjectSequence<logger_msgs.msg.dds.CameraConfiguration> getCameras()
   {
      return cameras_;
   }


}