/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/CameraConfiguration):
<pre>{@code
uint8 type
uint8 camera_id
string name
string identifier
}</pre>
*/
public class CameraConfiguration implements ROS2Message<CameraConfiguration>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::CameraConfiguration";

   private byte type_;
   private byte camera_id_;
   private final StringBuilder name_;
   private final StringBuilder identifier_;

   public CameraConfiguration()
   {
      name_ = new StringBuilder();
      identifier_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // camera_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * identifier_.length()) + 1; // identifier_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(type_);
      buffer.writeByte(camera_id_);
      buffer.writeString(name_);
      buffer.writeString(identifier_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      type_ = buffer.readByte();
      camera_id_ = buffer.readByte();
      buffer.readString(name_);
      buffer.readString(identifier_);

   }

   @Override
   public void set(CameraConfiguration from)
   {
      type_ = from.type_;
      camera_id_ = from.camera_id_;
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      identifier_.delete(0, identifier_.length());
      identifier_.insert(0, from.identifier_);

   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }

   public byte getCameraId()
   {
      return camera_id_;
   }

   public void setCameraId(byte camera_id_)
   {
      this.camera_id_ = camera_id_;
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   public StringBuilder getIdentifier()
   {
      return identifier_;
   }

   public java.lang.String getIdentifierAsString()
   {
      return identifier_.toString();
   }

   public void setIdentifier(java.lang.String s)
   {
      this.identifier_.delete(0, this.identifier_.length());
      this.identifier_.insert(0, s);
   }


}