/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/ChildLog):
<pre>{@code
string childName    # Name of the child log
Synchronization synchronization    # synchronization with the parent
LogProperties properties    # Properties of the child log
}</pre>
*/
public class ChildLog implements ROS2Message<ChildLog>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::ChildLog_";

   private final StringBuilder childName_; // Name of the child log
   private final logger_msgs.msg.dds.Synchronization synchronization_; // synchronization with the parent
   private final logger_msgs.msg.dds.LogProperties properties_; // Properties of the child log

   public ChildLog()
   {
      childName_ = new StringBuilder();
      synchronization_ = new logger_msgs.msg.dds.Synchronization();
      properties_ = new logger_msgs.msg.dds.LogProperties();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * childName_.length()) + 1; // childName_
      currentAlignment += synchronization_.calculateSizeBytes(currentAlignment);
      currentAlignment += properties_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(childName_);
      synchronization_.serialize(buffer);
      properties_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(childName_);
      synchronization_.deserialize(buffer);
      properties_.deserialize(buffer);

   }

   @Override
   public void set(ChildLog from)
   {
      childName_.delete(0, childName_.length());
      childName_.insert(0, from.childName_);
      synchronization_.set(from.synchronization_);
      properties_.set(from.properties_);

   }

   public StringBuilder getChildName()
   {
      return childName_;
   }

   public java.lang.String getChildNameAsString()
   {
      return childName_.toString();
   }

   public void setChildName(java.lang.String s)
   {
      this.childName_.delete(0, this.childName_.length());
      this.childName_.insert(0, s);
   }

   public logger_msgs.msg.dds.Synchronization getSynchronization()
   {
      return synchronization_;
   }

   public logger_msgs.msg.dds.LogProperties getProperties()
   {
      return properties_;
   }


}