/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/EnumType):
<pre>{@code
string name
string[255] enumValues
}</pre>
*/
public class EnumType implements ROS2Message<EnumType>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::EnumType_";

   private final StringBuilder name_;
   private final StringBuilder[] enumValues_;

   public EnumType()
   {
      name_ = new StringBuilder();
      enumValues_ = new StringBuilder[255];
      // enumValues is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < enumValues_.length; ++i)
      {
         enumValues_[i] = new StringBuilder();
      }

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += (255 * 1) + CDRBuffer.alignment(currentAlignment, (255 * 1)); // enumValues_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(name_);
      for (int i = 0; i < enumValues_.length; ++i)
      {
         buffer.writeString(enumValues_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(name_);
      for (int i = 0; i < enumValues_.length; ++i)
      {
         buffer.readString(enumValues_[i]);
      }

   }

   @Override
   public void set(EnumType from)
   {
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      for (int i = 0; i < enumValues_.length; ++i)
      {
         enumValues_[i] = from.enumValues_[i];
      }

   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   public StringBuilder[] getEnumValues()
   {
      return enumValues_;
   }


}