/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/HandshakeFileType):
<pre>{@code
uint8 PROTOBUFFER=0
uint8 IDL_YAML=1
uint8 IDL_CDR=2
}</pre>
*/
public class HandshakeFileType implements ROS2Message<HandshakeFileType>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::HandshakeFileType_";

   public static final byte PROTOBUFFER = 0;
   public static final byte IDL_YAML = 1;
   public static final byte IDL_CDR = 2;

   public HandshakeFileType()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public void set(HandshakeFileType from)
   {
   }

}