/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Handshake):
<pre>{@code
float64 dt
YoRegistryDefinition[] registries
YoVariableDefinition[] variables
JointDefinition[] joints
SCS1YoGraphicObjectMessage[] graphicObjects
SCS1YoGraphicObjectMessage[] artifacts
SCS2YoGraphicDefinitionMessage[] scs2YoGraphicDefinitions
EnumType[] enumTypes
ReferenceFrameInformation referenceFrameInformation
Summary summary
}</pre>
*/
public class Handshake implements ROS2Message<Handshake>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Handshake_";

   private double dt_;
   private final IDLObjectSequence<logger_msgs.msg.dds.YoRegistryDefinition> registries_;
   private final IDLObjectSequence<logger_msgs.msg.dds.YoVariableDefinition> variables_;
   private final IDLObjectSequence<logger_msgs.msg.dds.JointDefinition> joints_;
   private final IDLObjectSequence<logger_msgs.msg.dds.SCS1YoGraphicObjectMessage> graphicObjects_;
   private final IDLObjectSequence<logger_msgs.msg.dds.SCS1YoGraphicObjectMessage> artifacts_;
   private final IDLObjectSequence<logger_msgs.msg.dds.SCS2YoGraphicDefinitionMessage> scs2YoGraphicDefinitions_;
   private final IDLObjectSequence<logger_msgs.msg.dds.EnumType> enumTypes_;
   private final logger_msgs.msg.dds.ReferenceFrameInformation referenceFrameInformation_;
   private final logger_msgs.msg.dds.Summary summary_;

   public Handshake()
   {
      registries_ = new IDLObjectSequence<logger_msgs.msg.dds.YoRegistryDefinition>(logger_msgs.msg.dds.YoRegistryDefinition.class);
      variables_ = new IDLObjectSequence<logger_msgs.msg.dds.YoVariableDefinition>(logger_msgs.msg.dds.YoVariableDefinition.class);
      joints_ = new IDLObjectSequence<logger_msgs.msg.dds.JointDefinition>(logger_msgs.msg.dds.JointDefinition.class);
      graphicObjects_ = new IDLObjectSequence<logger_msgs.msg.dds.SCS1YoGraphicObjectMessage>(logger_msgs.msg.dds.SCS1YoGraphicObjectMessage.class);
      artifacts_ = new IDLObjectSequence<logger_msgs.msg.dds.SCS1YoGraphicObjectMessage>(logger_msgs.msg.dds.SCS1YoGraphicObjectMessage.class);
      scs2YoGraphicDefinitions_ = new IDLObjectSequence<logger_msgs.msg.dds.SCS2YoGraphicDefinitionMessage>(logger_msgs.msg.dds.SCS2YoGraphicDefinitionMessage.class);
      enumTypes_ = new IDLObjectSequence<logger_msgs.msg.dds.EnumType>(logger_msgs.msg.dds.EnumType.class);
      referenceFrameInformation_ = new logger_msgs.msg.dds.ReferenceFrameInformation();
      summary_ = new logger_msgs.msg.dds.Summary();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // dt_
      currentAlignment += registries_.calculateSizeBytes(currentAlignment);
      currentAlignment += variables_.calculateSizeBytes(currentAlignment);
      currentAlignment += joints_.calculateSizeBytes(currentAlignment);
      currentAlignment += graphicObjects_.calculateSizeBytes(currentAlignment);
      currentAlignment += artifacts_.calculateSizeBytes(currentAlignment);
      currentAlignment += scs2YoGraphicDefinitions_.calculateSizeBytes(currentAlignment);
      currentAlignment += enumTypes_.calculateSizeBytes(currentAlignment);
      currentAlignment += referenceFrameInformation_.calculateSizeBytes(currentAlignment);
      currentAlignment += summary_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(dt_);
      registries_.serialize(buffer);
      variables_.serialize(buffer);
      joints_.serialize(buffer);
      graphicObjects_.serialize(buffer);
      artifacts_.serialize(buffer);
      scs2YoGraphicDefinitions_.serialize(buffer);
      enumTypes_.serialize(buffer);
      referenceFrameInformation_.serialize(buffer);
      summary_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      dt_ = buffer.readDouble();
      registries_.deserialize(buffer);
      variables_.deserialize(buffer);
      joints_.deserialize(buffer);
      graphicObjects_.deserialize(buffer);
      artifacts_.deserialize(buffer);
      scs2YoGraphicDefinitions_.deserialize(buffer);
      enumTypes_.deserialize(buffer);
      referenceFrameInformation_.deserialize(buffer);
      summary_.deserialize(buffer);

   }

   @Override
   public void set(Handshake from)
   {
      dt_ = from.dt_;
      registries_.set(from.registries_);
      variables_.set(from.variables_);
      joints_.set(from.joints_);
      graphicObjects_.set(from.graphicObjects_);
      artifacts_.set(from.artifacts_);
      scs2YoGraphicDefinitions_.set(from.scs2YoGraphicDefinitions_);
      enumTypes_.set(from.enumTypes_);
      referenceFrameInformation_.set(from.referenceFrameInformation_);
      summary_.set(from.summary_);

   }

   public double getDt()
   {
      return dt_;
   }

   public void setDt(double dt_)
   {
      this.dt_ = dt_;
   }

   public IDLObjectSequence<logger_msgs.msg.dds.YoRegistryDefinition> getRegistries()
   {
      return registries_;
   }

   public IDLObjectSequence<logger_msgs.msg.dds.YoVariableDefinition> getVariables()
   {
      return variables_;
   }

   public IDLObjectSequence<logger_msgs.msg.dds.JointDefinition> getJoints()
   {
      return joints_;
   }

   public IDLObjectSequence<logger_msgs.msg.dds.SCS1YoGraphicObjectMessage> getGraphicObjects()
   {
      return graphicObjects_;
   }

   public IDLObjectSequence<logger_msgs.msg.dds.SCS1YoGraphicObjectMessage> getArtifacts()
   {
      return artifacts_;
   }

   public IDLObjectSequence<logger_msgs.msg.dds.SCS2YoGraphicDefinitionMessage> getScs2YoGraphicDefinitions()
   {
      return scs2YoGraphicDefinitions_;
   }

   public IDLObjectSequence<logger_msgs.msg.dds.EnumType> getEnumTypes()
   {
      return enumTypes_;
   }

   public logger_msgs.msg.dds.ReferenceFrameInformation getReferenceFrameInformation()
   {
      return referenceFrameInformation_;
   }

   public logger_msgs.msg.dds.Summary getSummary()
   {
      return summary_;
   }


}