/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/HandshakeFileType):
<pre>{@code
uint8 IDL_YAML=1
uint8 IDL_CDR=2
uint8 type 0}</pre>
*/
public class HandshakeFileType implements ROS2Message<HandshakeFileType>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::HandshakeFileType";

   public static final byte IDL_YAML = 1;
   public static final byte IDL_CDR = 2;
   private byte type_;

   public HandshakeFileType()
   {
      type_ = (byte) 0;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      type_ = buffer.readByte();

   }

   @Override
   public void set(HandshakeFileType from)
   {
      type_ = from.type_;

   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }


}