/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Host):
<pre>{@code
string hostname
uint16 port
uint8[128] cameras
}</pre>
*/
public class Host implements ROS2Message<Host>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Host_";

   private final StringBuilder hostname_;
   private short port_;
   private final byte[] cameras_;

   public Host()
   {
      hostname_ = new StringBuilder();
      cameras_ = new byte[128];

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * hostname_.length()) + 1; // hostname_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // port_
      currentAlignment += (128 * 1) + CDRBuffer.alignment(currentAlignment, (128 * 1)); // cameras_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(hostname_);
      buffer.writeShort(port_);
      for (int i = 0; i < cameras_.length; ++i)
      {
         buffer.writeByte(cameras_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(hostname_);
      port_ = buffer.readShort();
      for (int i = 0; i < cameras_.length; ++i)
      {
         cameras_[i] = buffer.readByte();
      }

   }

   @Override
   public void set(Host from)
   {
      hostname_.delete(0, hostname_.length());
      hostname_.insert(0, from.hostname_);
      port_ = from.port_;
      for (int i = 0; i < cameras_.length; ++i)
      {
         cameras_[i] = from.cameras_[i];
      }

   }

   public StringBuilder getHostname()
   {
      return hostname_;
   }

   public java.lang.String getHostnameAsString()
   {
      return hostname_.toString();
   }

   public void setHostname(java.lang.String s)
   {
      this.hostname_.delete(0, this.hostname_.length());
      this.hostname_.insert(0, s);
   }

   public short getPort()
   {
      return port_;
   }

   public void setPort(short port_)
   {
      this.port_ = port_;
   }

   public byte[] getCameras()
   {
      return cameras_;
   }


}