/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/JointDefinition):
<pre>{@code
string name
uint8 type
}</pre>
*/
public class JointDefinition implements ROS2Message<JointDefinition>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::JointDefinition";

   private final StringBuilder name_;
   private byte type_;

   public JointDefinition()
   {
      name_ = new StringBuilder();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(name_);
      buffer.writeByte(type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(name_);
      type_ = buffer.readByte();

   }

   @Override
   public void set(JointDefinition from)
   {
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      type_ = from.type_;

   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }


}