/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/LoadStatus):
<pre>{@code
uint8 NoParameter=0
uint8 Unloaded=1
uint8 Default=2
uint8 Loaded=3
}</pre>
*/
public class LoadStatus implements ROS2Message<LoadStatus>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::LoadStatus";

   public static final byte NOPARAMETER = 0;
   public static final byte UNLOADED = 1;
   public static final byte DEFAULT = 2;
   public static final byte LOADED = 3;

   public LoadStatus()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
   }

   @Override
   public void set(LoadStatus from)
   {
   }

}