/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/LogData):
<pre>{@code
int64 uid
int64 timestamp
int64 transmitTime
uint8 type
int32 registry
int32 offset
int32 numberOfVariables
uint8[] data
float64[] jointStates
}</pre>
*/
public class LogData implements ROS2Message<LogData>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::LogData";

   private long uid_;
   private long timestamp_;
   private long transmitTime_;
   private byte type_;
   private int registry_;
   private int offset_;
   private int numberOfVariables_;
   private final IDLByteSequence data_;
   private final IDLDoubleSequence jointStates_;

   public LogData()
   {
      data_ = new IDLByteSequence();
      jointStates_ = new IDLDoubleSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // uid_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // timestamp_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // transmitTime_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // registry_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // offset_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // numberOfVariables_
      currentAlignment += data_.calculateSizeBytes(currentAlignment);
      currentAlignment += jointStates_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(uid_);
      buffer.writeLong(timestamp_);
      buffer.writeLong(transmitTime_);
      buffer.writeByte(type_);
      buffer.writeInt(registry_);
      buffer.writeInt(offset_);
      buffer.writeInt(numberOfVariables_);
      data_.serialize(buffer);
      jointStates_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      uid_ = buffer.readLong();
      timestamp_ = buffer.readLong();
      transmitTime_ = buffer.readLong();
      type_ = buffer.readByte();
      registry_ = buffer.readInt();
      offset_ = buffer.readInt();
      numberOfVariables_ = buffer.readInt();
      data_.deserialize(buffer);
      jointStates_.deserialize(buffer);

   }

   @Override
   public void set(LogData from)
   {
      uid_ = from.uid_;
      timestamp_ = from.timestamp_;
      transmitTime_ = from.transmitTime_;
      type_ = from.type_;
      registry_ = from.registry_;
      offset_ = from.offset_;
      numberOfVariables_ = from.numberOfVariables_;
      data_.set(from.data_);
      jointStates_.set(from.jointStates_);

   }

   public long getUid()
   {
      return uid_;
   }

   public void setUid(long uid_)
   {
      this.uid_ = uid_;
   }

   public long getTimestamp()
   {
      return timestamp_;
   }

   public void setTimestamp(long timestamp_)
   {
      this.timestamp_ = timestamp_;
   }

   public long getTransmitTime()
   {
      return transmitTime_;
   }

   public void setTransmitTime(long transmitTime_)
   {
      this.transmitTime_ = transmitTime_;
   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }

   public int getRegistry()
   {
      return registry_;
   }

   public void setRegistry(int registry_)
   {
      this.registry_ = registry_;
   }

   public int getOffset()
   {
      return offset_;
   }

   public void setOffset(int offset_)
   {
      this.offset_ = offset_;
   }

   public int getNumberOfVariables()
   {
      return numberOfVariables_;
   }

   public void setNumberOfVariables(int numberOfVariables_)
   {
      this.numberOfVariables_ = numberOfVariables_;
   }

   public IDLByteSequence getData()
   {
      return data_;
   }

   public IDLDoubleSequence getJointStates()
   {
      return jointStates_;
   }


}