/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/LogDataType):
<pre>{@code
uint8 KEEP_ALIVE_PACKET=0
uint8 DATA_PACKET=1
uint8 VIDEO_PACKET=2
uint8 type 0}</pre>
*/
public class LogDataType implements ROS2Message<LogDataType>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::LogDataType_";

   public static final byte KEEP_ALIVE_PACKET = 0;
   public static final byte DATA_PACKET = 1;
   public static final byte VIDEO_PACKET = 2;
   private byte type_;

   public LogDataType()
   {
      type_ = (byte) 0;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      type_ = buffer.readByte();

   }

   @Override
   public void set(LogDataType from)
   {
      type_ = from.type_;

   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }


}