/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/LogProperties):
<pre>{@code
string version    # Version of the properties
string name    # Name of this log
Variables variables
Model model
string timestamp    # When was this log taken

Camera[] cameras

# Backward compatibility options
Video video    # Old timebase option

ChildLog[] childLogs
}</pre>
*/
public class LogProperties implements ROS2Message<LogProperties>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::LogProperties_";

   private final StringBuilder version_; // Version of the properties
   private final StringBuilder name_; // Name of this log
   private final logger_msgs.msg.dds.Variables variables_;
   private final logger_msgs.msg.dds.Model model_;
   private final StringBuilder timestamp_; // When was this log taken
   private final IDLObjectSequence<logger_msgs.msg.dds.Camera> cameras_;
   /**
      Backward compatibility options
   */
   private final logger_msgs.msg.dds.Video video_; // Old timebase option
   private final IDLObjectSequence<logger_msgs.msg.dds.ChildLog> childLogs_;

   public LogProperties()
   {
      version_ = new StringBuilder();
      name_ = new StringBuilder();
      variables_ = new logger_msgs.msg.dds.Variables();
      model_ = new logger_msgs.msg.dds.Model();
      timestamp_ = new StringBuilder();
      cameras_ = new IDLObjectSequence<logger_msgs.msg.dds.Camera>(logger_msgs.msg.dds.Camera.class);
      video_ = new logger_msgs.msg.dds.Video();
      childLogs_ = new IDLObjectSequence<logger_msgs.msg.dds.ChildLog>(logger_msgs.msg.dds.ChildLog.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * version_.length()) + 1; // version_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += variables_.calculateSizeBytes(currentAlignment);
      currentAlignment += model_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * timestamp_.length()) + 1; // timestamp_
      currentAlignment += cameras_.calculateSizeBytes(currentAlignment);
      currentAlignment += video_.calculateSizeBytes(currentAlignment);
      currentAlignment += childLogs_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(version_);
      buffer.writeString(name_);
      variables_.serialize(buffer);
      model_.serialize(buffer);
      buffer.writeString(timestamp_);
      cameras_.serialize(buffer);
      video_.serialize(buffer);
      childLogs_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(version_);
      buffer.readString(name_);
      variables_.deserialize(buffer);
      model_.deserialize(buffer);
      buffer.readString(timestamp_);
      cameras_.deserialize(buffer);
      video_.deserialize(buffer);
      childLogs_.deserialize(buffer);

   }

   @Override
   public void set(LogProperties from)
   {
      version_.delete(0, version_.length());
      version_.insert(0, from.version_);
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      variables_.set(from.variables_);
      model_.set(from.model_);
      timestamp_.delete(0, timestamp_.length());
      timestamp_.insert(0, from.timestamp_);
      cameras_.set(from.cameras_);
      video_.set(from.video_);
      childLogs_.set(from.childLogs_);

   }

   public StringBuilder getVersion()
   {
      return version_;
   }

   public java.lang.String getVersionAsString()
   {
      return version_.toString();
   }

   public void setVersion(java.lang.String s)
   {
      this.version_.delete(0, this.version_.length());
      this.version_.insert(0, s);
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   public logger_msgs.msg.dds.Variables getVariables()
   {
      return variables_;
   }

   public logger_msgs.msg.dds.Model getModel()
   {
      return model_;
   }

   public StringBuilder getTimestamp()
   {
      return timestamp_;
   }

   public java.lang.String getTimestampAsString()
   {
      return timestamp_.toString();
   }

   public void setTimestamp(java.lang.String s)
   {
      this.timestamp_.delete(0, this.timestamp_.length());
      this.timestamp_.insert(0, s);
   }

   public IDLObjectSequence<logger_msgs.msg.dds.Camera> getCameras()
   {
      return cameras_;
   }

   public logger_msgs.msg.dds.Video getVideo()
   {
      return video_;
   }

   public IDLObjectSequence<logger_msgs.msg.dds.ChildLog> getChildLogs()
   {
      return childLogs_;
   }


}