/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/ModelFileDescription):
<pre>{@code
bool hasModel
string name
string modelLoaderClass
string[255] resourceDirectories

int32 modelFileSize

bool hasResourceZip
int32 resourceZipSize
}</pre>
*/
public class ModelFileDescription implements ROS2Message<ModelFileDescription>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::ModelFileDescription_";

   private boolean hasModel_;
   private final StringBuilder name_;
   private final StringBuilder modelLoaderClass_;
   private final StringBuilder[] resourceDirectories_;
   private int modelFileSize_;
   private boolean hasResourceZip_;
   private int resourceZipSize_;

   public ModelFileDescription()
   {
      hasModel_ = (boolean) false;
      name_ = new StringBuilder();
      modelLoaderClass_ = new StringBuilder();
      resourceDirectories_ = new StringBuilder[255];
      // resourceDirectories is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < resourceDirectories_.length; ++i)
      {
         resourceDirectories_[i] = new StringBuilder();
      }
      hasResourceZip_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // hasModel_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * modelLoaderClass_.length()) + 1; // modelLoaderClass_
      currentAlignment += (255 * 1) + CDRBuffer.alignment(currentAlignment, (255 * 1)); // resourceDirectories_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // modelFileSize_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // hasResourceZip_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // resourceZipSize_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(hasModel_);
      buffer.writeString(name_);
      buffer.writeString(modelLoaderClass_);
      for (int i = 0; i < resourceDirectories_.length; ++i)
      {
         buffer.writeString(resourceDirectories_[i]);
      }
      buffer.writeInt(modelFileSize_);
      buffer.writeBoolean(hasResourceZip_);
      buffer.writeInt(resourceZipSize_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      hasModel_ = buffer.readBoolean();
      buffer.readString(name_);
      buffer.readString(modelLoaderClass_);
      for (int i = 0; i < resourceDirectories_.length; ++i)
      {
         buffer.readString(resourceDirectories_[i]);
      }
      modelFileSize_ = buffer.readInt();
      hasResourceZip_ = buffer.readBoolean();
      resourceZipSize_ = buffer.readInt();

   }

   @Override
   public void set(ModelFileDescription from)
   {
      hasModel_ = from.hasModel_;
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      modelLoaderClass_.delete(0, modelLoaderClass_.length());
      modelLoaderClass_.insert(0, from.modelLoaderClass_);
      for (int i = 0; i < resourceDirectories_.length; ++i)
      {
         resourceDirectories_[i] = from.resourceDirectories_[i];
      }
      modelFileSize_ = from.modelFileSize_;
      hasResourceZip_ = from.hasResourceZip_;
      resourceZipSize_ = from.resourceZipSize_;

   }

   public boolean getHasModel()
   {
      return hasModel_;
   }

   public void setHasModel(boolean hasModel_)
   {
      this.hasModel_ = hasModel_;
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   public StringBuilder getModelLoaderClass()
   {
      return modelLoaderClass_;
   }

   public java.lang.String getModelLoaderClassAsString()
   {
      return modelLoaderClass_.toString();
   }

   public void setModelLoaderClass(java.lang.String s)
   {
      this.modelLoaderClass_.delete(0, this.modelLoaderClass_.length());
      this.modelLoaderClass_.insert(0, s);
   }

   public StringBuilder[] getResourceDirectories()
   {
      return resourceDirectories_;
   }

   public int getModelFileSize()
   {
      return modelFileSize_;
   }

   public void setModelFileSize(int modelFileSize_)
   {
      this.modelFileSize_ = modelFileSize_;
   }

   public boolean getHasResourceZip()
   {
      return hasResourceZip_;
   }

   public void setHasResourceZip(boolean hasResourceZip_)
   {
      this.hasResourceZip_ = hasResourceZip_;
   }

   public int getResourceZipSize()
   {
      return resourceZipSize_;
   }

   public void setResourceZipSize(int resourceZipSize_)
   {
      this.resourceZipSize_ = resourceZipSize_;
   }


}