/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Model):
<pre>{@code
string loader    # Loader class
string path    # Path
string name    # Model file name
string resourceBundle    # Resource bundle zip file name
string[] resourceDirectoriesList    # List of resource directories
}</pre>
*/
public class Model implements ROS2Message<Model>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Model_";

   private final StringBuilder loader_; // Loader class
   private final StringBuilder path_; // Path
   private final StringBuilder name_; // Model file name
   private final StringBuilder resourceBundle_; // Resource bundle zip file name
   private final IDLStringSequence resourceDirectoriesList_; // List of resource directories

   public Model()
   {
      loader_ = new StringBuilder();
      path_ = new StringBuilder();
      name_ = new StringBuilder();
      resourceBundle_ = new StringBuilder();
      resourceDirectoriesList_ = new IDLStringSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * loader_.length()) + 1; // loader_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * path_.length()) + 1; // path_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * resourceBundle_.length()) + 1; // resourceBundle_
      currentAlignment += resourceDirectoriesList_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(loader_);
      buffer.writeString(path_);
      buffer.writeString(name_);
      buffer.writeString(resourceBundle_);
      resourceDirectoriesList_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(loader_);
      buffer.readString(path_);
      buffer.readString(name_);
      buffer.readString(resourceBundle_);
      resourceDirectoriesList_.deserialize(buffer);

   }

   @Override
   public void set(Model from)
   {
      loader_.delete(0, loader_.length());
      loader_.insert(0, from.loader_);
      path_.delete(0, path_.length());
      path_.insert(0, from.path_);
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      resourceBundle_.delete(0, resourceBundle_.length());
      resourceBundle_.insert(0, from.resourceBundle_);
      resourceDirectoriesList_.set(from.resourceDirectoriesList_);

   }

   public StringBuilder getLoader()
   {
      return loader_;
   }

   public java.lang.String getLoaderAsString()
   {
      return loader_.toString();
   }

   public void setLoader(java.lang.String s)
   {
      this.loader_.delete(0, this.loader_.length());
      this.loader_.insert(0, s);
   }

   public StringBuilder getPath()
   {
      return path_;
   }

   public java.lang.String getPathAsString()
   {
      return path_.toString();
   }

   public void setPath(java.lang.String s)
   {
      this.path_.delete(0, this.path_.length());
      this.path_.insert(0, s);
   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   public StringBuilder getResourceBundle()
   {
      return resourceBundle_;
   }

   public java.lang.String getResourceBundleAsString()
   {
      return resourceBundle_.toString();
   }

   public void setResourceBundle(java.lang.String s)
   {
      this.resourceBundle_.delete(0, this.resourceBundle_.length());
      this.resourceBundle_.insert(0, s);
   }

   public IDLStringSequence getResourceDirectoriesList()
   {
      return resourceDirectoriesList_;
   }


}