/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/ReferenceFrameInformation):
<pre>{@code
uint32[8192] frameIndices
string[8192] frameNames
}</pre>
*/
public class ReferenceFrameInformation implements ROS2Message<ReferenceFrameInformation>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::ReferenceFrameInformation_";

   private final int[] frameIndices_;
   private final StringBuilder[] frameNames_;

   public ReferenceFrameInformation()
   {
      frameIndices_ = new int[8192];
      frameNames_ = new StringBuilder[8192];
      // frameNames is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < frameNames_.length; ++i)
      {
         frameNames_[i] = new StringBuilder();
      }

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += (8192 * 4) + CDRBuffer.alignment(currentAlignment, (8192 * 4)); // frameIndices_
      currentAlignment += (8192 * 1) + CDRBuffer.alignment(currentAlignment, (8192 * 1)); // frameNames_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      for (int i = 0; i < frameIndices_.length; ++i)
      {
         buffer.writeInt(frameIndices_[i]);
      }
      for (int i = 0; i < frameNames_.length; ++i)
      {
         buffer.writeString(frameNames_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      for (int i = 0; i < frameIndices_.length; ++i)
      {
         frameIndices_[i] = buffer.readInt();
      }
      for (int i = 0; i < frameNames_.length; ++i)
      {
         buffer.readString(frameNames_[i]);
      }

   }

   @Override
   public void set(ReferenceFrameInformation from)
   {
      for (int i = 0; i < frameIndices_.length; ++i)
      {
         frameIndices_[i] = from.frameIndices_[i];
      }
      for (int i = 0; i < frameNames_.length; ++i)
      {
         frameNames_[i] = from.frameNames_[i];
      }

   }

   public int[] getFrameIndices()
   {
      return frameIndices_;
   }

   public StringBuilder[] getFrameNames()
   {
      return frameNames_;
   }


}