/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/SCS1AppearanceDefinitionMessage):
<pre>{@code
float64 r
float64 g
float64 b

float64 transparency
}</pre>
*/
public class SCS1AppearanceDefinitionMessage implements ROS2Message<SCS1AppearanceDefinitionMessage>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::SCS1AppearanceDefinitionMessage_";

   private double r_;
   private double g_;
   private double b_;
   private double transparency_;

   public SCS1AppearanceDefinitionMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // r_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // g_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // b_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // transparency_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(r_);
      buffer.writeDouble(g_);
      buffer.writeDouble(b_);
      buffer.writeDouble(transparency_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      r_ = buffer.readDouble();
      g_ = buffer.readDouble();
      b_ = buffer.readDouble();
      transparency_ = buffer.readDouble();

   }

   @Override
   public void set(SCS1AppearanceDefinitionMessage from)
   {
      r_ = from.r_;
      g_ = from.g_;
      b_ = from.b_;
      transparency_ = from.transparency_;

   }

   public double getR()
   {
      return r_;
   }

   public void setR(double r_)
   {
      this.r_ = r_;
   }

   public double getG()
   {
      return g_;
   }

   public void setG(double g_)
   {
      this.g_ = g_;
   }

   public double getB()
   {
      return b_;
   }

   public void setB(double b_)
   {
      this.b_ = b_;
   }

   public double getTransparency()
   {
      return transparency_;
   }

   public void setTransparency(double transparency_)
   {
      this.transparency_ = transparency_;
   }


}