/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/SCS2YoGraphicDefinitionMessage):
<pre>{@code
string[64] fieldNames
string[64] fieldValues
}</pre>
*/
public class SCS2YoGraphicDefinitionMessage implements ROS2Message<SCS2YoGraphicDefinitionMessage>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::SCS2YoGraphicDefinitionMessage_";

   private final StringBuilder[] fieldNames_;
   private final StringBuilder[] fieldValues_;

   public SCS2YoGraphicDefinitionMessage()
   {
      fieldNames_ = new StringBuilder[64];
      // fieldNames is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < fieldNames_.length; ++i)
      {
         fieldNames_[i] = new StringBuilder();
      }
      fieldValues_ = new StringBuilder[64];
      // fieldValues is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < fieldValues_.length; ++i)
      {
         fieldValues_[i] = new StringBuilder();
      }

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += (64 * 1) + CDRBuffer.alignment(currentAlignment, (64 * 1)); // fieldNames_
      currentAlignment += (64 * 1) + CDRBuffer.alignment(currentAlignment, (64 * 1)); // fieldValues_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      for (int i = 0; i < fieldNames_.length; ++i)
      {
         buffer.writeString(fieldNames_[i]);
      }
      for (int i = 0; i < fieldValues_.length; ++i)
      {
         buffer.writeString(fieldValues_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      for (int i = 0; i < fieldNames_.length; ++i)
      {
         buffer.readString(fieldNames_[i]);
      }
      for (int i = 0; i < fieldValues_.length; ++i)
      {
         buffer.readString(fieldValues_[i]);
      }

   }

   @Override
   public void set(SCS2YoGraphicDefinitionMessage from)
   {
      for (int i = 0; i < fieldNames_.length; ++i)
      {
         fieldNames_[i] = from.fieldNames_[i];
      }
      for (int i = 0; i < fieldValues_.length; ++i)
      {
         fieldValues_[i] = from.fieldValues_[i];
      }

   }

   public StringBuilder[] getFieldNames()
   {
      return fieldNames_;
   }

   public StringBuilder[] getFieldValues()
   {
      return fieldValues_;
   }


}