/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/SCS2YoGraphicDefinitionMessage):
<pre>{@code
string[] fieldNames
string[] fieldValues
}</pre>
*/
public class SCS2YoGraphicDefinitionMessage implements ROS2Message<SCS2YoGraphicDefinitionMessage>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::SCS2YoGraphicDefinitionMessage";

   private final IDLStringSequence fieldNames_;
   private final IDLStringSequence fieldValues_;

   public SCS2YoGraphicDefinitionMessage()
   {
      fieldNames_ = new IDLStringSequence();
      fieldValues_ = new IDLStringSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += fieldNames_.calculateSizeBytes(currentAlignment);
      currentAlignment += fieldValues_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      fieldNames_.serialize(buffer);
      fieldValues_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      fieldNames_.deserialize(buffer);
      fieldValues_.deserialize(buffer);

   }

   @Override
   public void set(SCS2YoGraphicDefinitionMessage from)
   {
      fieldNames_.set(from.fieldNames_);
      fieldValues_.set(from.fieldValues_);

   }

   public IDLStringSequence getFieldNames()
   {
      return fieldNames_;
   }

   public IDLStringSequence getFieldValues()
   {
      return fieldValues_;
   }


}