/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/StaticHostList):
<pre>{@code
bool disableAutoDiscovery
Host[128] hosts
}</pre>
*/
public class StaticHostList implements ROS2Message<StaticHostList>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::StaticHostList_";

   private boolean disableAutoDiscovery_;
   private final logger_msgs.msg.dds.Host[] hosts_;

   public StaticHostList()
   {
      disableAutoDiscovery_ = (boolean) false;
      hosts_ = new logger_msgs.msg.dds.Host[128];
      // hosts is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < hosts_.length; ++i)
      {
         hosts_[i] = new logger_msgs.msg.dds.Host();
      }

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // disableAutoDiscovery_
      for (int i = 0; i < hosts_.length; ++i)
      {
         currentAlignment += hosts_[i].calculateSizeBytes(currentAlignment);
      }

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(disableAutoDiscovery_);
      for (int i = 0; i < hosts_.length; ++i)
      {
         hosts_[i].serialize(buffer);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      disableAutoDiscovery_ = buffer.readBoolean();
      for (int i = 0; i < hosts_.length; ++i)
      {
         hosts_[i].deserialize(buffer);
      }

   }

   @Override
   public void set(StaticHostList from)
   {
      disableAutoDiscovery_ = from.disableAutoDiscovery_;
      for (int i = 0; i < hosts_.length; ++i)
      {
         hosts_[i].set(from.hosts_[i]);
      }

   }

   public boolean getDisableAutoDiscovery()
   {
      return disableAutoDiscovery_;
   }

   public void setDisableAutoDiscovery(boolean disableAutoDiscovery_)
   {
      this.disableAutoDiscovery_ = disableAutoDiscovery_;
   }

   public logger_msgs.msg.dds.Host[] getHosts()
   {
      return hosts_;
   }


}