/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Summary):
<pre>{@code
bool createSummary
string summaryTriggerVariable
string[128] summarizedVariables
}</pre>
*/
public class Summary implements ROS2Message<Summary>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Summary_";

   private boolean createSummary_;
   private final StringBuilder summaryTriggerVariable_;
   private final StringBuilder[] summarizedVariables_;

   public Summary()
   {
      createSummary_ = (boolean) false;
      summaryTriggerVariable_ = new StringBuilder();
      summarizedVariables_ = new StringBuilder[128];
      // summarizedVariables is defined as a fixed-size array, so it is pre-allocated.
      for (int i = 0; i < summarizedVariables_.length; ++i)
      {
         summarizedVariables_[i] = new StringBuilder();
      }

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // createSummary_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * summaryTriggerVariable_.length()) + 1; // summaryTriggerVariable_
      currentAlignment += (128 * 1) + CDRBuffer.alignment(currentAlignment, (128 * 1)); // summarizedVariables_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(createSummary_);
      buffer.writeString(summaryTriggerVariable_);
      for (int i = 0; i < summarizedVariables_.length; ++i)
      {
         buffer.writeString(summarizedVariables_[i]);
      }

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      createSummary_ = buffer.readBoolean();
      buffer.readString(summaryTriggerVariable_);
      for (int i = 0; i < summarizedVariables_.length; ++i)
      {
         buffer.readString(summarizedVariables_[i]);
      }

   }

   @Override
   public void set(Summary from)
   {
      createSummary_ = from.createSummary_;
      summaryTriggerVariable_.delete(0, summaryTriggerVariable_.length());
      summaryTriggerVariable_.insert(0, from.summaryTriggerVariable_);
      for (int i = 0; i < summarizedVariables_.length; ++i)
      {
         summarizedVariables_[i] = from.summarizedVariables_[i];
      }

   }

   public boolean getCreateSummary()
   {
      return createSummary_;
   }

   public void setCreateSummary(boolean createSummary_)
   {
      this.createSummary_ = createSummary_;
   }

   public StringBuilder getSummaryTriggerVariable()
   {
      return summaryTriggerVariable_;
   }

   public java.lang.String getSummaryTriggerVariableAsString()
   {
      return summaryTriggerVariable_.toString();
   }

   public void setSummaryTriggerVariable(java.lang.String s)
   {
      this.summaryTriggerVariable_.delete(0, this.summaryTriggerVariable_.length());
      this.summaryTriggerVariable_.insert(0, s);
   }

   public StringBuilder[] getSummarizedVariables()
   {
      return summarizedVariables_;
   }


}