/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Timestamp):
<pre>{@code
int64 timestamp
}</pre>
*/
public class Timestamp implements ROS2Message<Timestamp>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Timestamp_";

   private long timestamp_;

   public Timestamp()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // timestamp_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(timestamp_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      timestamp_ = buffer.readLong();

   }

   @Override
   public void set(Timestamp from)
   {
      timestamp_ = from.timestamp_;

   }

   public long getTimestamp()
   {
      return timestamp_;
   }

   public void setTimestamp(long timestamp_)
   {
      this.timestamp_ = timestamp_;
   }


}