/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Variables):
<pre>{@code
uint8 handshakeFileType
string handshake    # Handshake file name
string data    # Data file name
string summary    # Summary file name
string index    # Variable index file
bool timestamped    # Does the index contain timestamps
bool compressed    # Is the data compressed
}</pre>
*/
public class Variables implements ROS2Message<Variables>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Variables_";

   private byte handshakeFileType_;
   private final StringBuilder handshake_; // Handshake file name
   private final StringBuilder data_; // Data file name
   private final StringBuilder summary_; // Summary file name
   private final StringBuilder index_; // Variable index file
   private boolean timestamped_; // Does the index contain timestamps
   private boolean compressed_; // Is the data compressed

   public Variables()
   {
      handshake_ = new StringBuilder();
      data_ = new StringBuilder();
      summary_ = new StringBuilder();
      index_ = new StringBuilder();
      timestamped_ = (boolean) false;
      compressed_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // handshakeFileType_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * handshake_.length()) + 1; // handshake_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * data_.length()) + 1; // data_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * summary_.length()) + 1; // summary_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * index_.length()) + 1; // index_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // timestamped_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // compressed_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(handshakeFileType_);
      buffer.writeString(handshake_);
      buffer.writeString(data_);
      buffer.writeString(summary_);
      buffer.writeString(index_);
      buffer.writeBoolean(timestamped_);
      buffer.writeBoolean(compressed_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      handshakeFileType_ = buffer.readByte();
      buffer.readString(handshake_);
      buffer.readString(data_);
      buffer.readString(summary_);
      buffer.readString(index_);
      timestamped_ = buffer.readBoolean();
      compressed_ = buffer.readBoolean();

   }

   @Override
   public void set(Variables from)
   {
      handshakeFileType_ = from.handshakeFileType_;
      handshake_.delete(0, handshake_.length());
      handshake_.insert(0, from.handshake_);
      data_.delete(0, data_.length());
      data_.insert(0, from.data_);
      summary_.delete(0, summary_.length());
      summary_.insert(0, from.summary_);
      index_.delete(0, index_.length());
      index_.insert(0, from.index_);
      timestamped_ = from.timestamped_;
      compressed_ = from.compressed_;

   }

   public byte getHandshakeFileType()
   {
      return handshakeFileType_;
   }

   public void setHandshakeFileType(byte handshakeFileType_)
   {
      this.handshakeFileType_ = handshakeFileType_;
   }

   public StringBuilder getHandshake()
   {
      return handshake_;
   }

   public java.lang.String getHandshakeAsString()
   {
      return handshake_.toString();
   }

   public void setHandshake(java.lang.String s)
   {
      this.handshake_.delete(0, this.handshake_.length());
      this.handshake_.insert(0, s);
   }

   public StringBuilder getData()
   {
      return data_;
   }

   public java.lang.String getDataAsString()
   {
      return data_.toString();
   }

   public void setData(java.lang.String s)
   {
      this.data_.delete(0, this.data_.length());
      this.data_.insert(0, s);
   }

   public StringBuilder getSummary()
   {
      return summary_;
   }

   public java.lang.String getSummaryAsString()
   {
      return summary_.toString();
   }

   public void setSummary(java.lang.String s)
   {
      this.summary_.delete(0, this.summary_.length());
      this.summary_.insert(0, s);
   }

   public StringBuilder getIndex()
   {
      return index_;
   }

   public java.lang.String getIndexAsString()
   {
      return index_.toString();
   }

   public void setIndex(java.lang.String s)
   {
      this.index_.delete(0, this.index_.length());
      this.index_.insert(0, s);
   }

   public boolean getTimestamped()
   {
      return timestamped_;
   }

   public void setTimestamped(boolean timestamped_)
   {
      this.timestamped_ = timestamped_;
   }

   public boolean getCompressed()
   {
      return compressed_;
   }

   public void setCompressed(boolean compressed_)
   {
      this.compressed_ = compressed_;
   }


}