/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/Video):
<pre>{@code
# Old option, not used anymore for new logs
bool hasTimebase
}</pre>
*/
public class Video implements ROS2Message<Video>
{
   public static final java.lang.String name = "logger_msgs::msg::dds_::Video_";

   /**
      Old option, not used anymore for new logs
   */
   private boolean hasTimebase_;

   public Video()
   {
      hasTimebase_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // hasTimebase_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(hasTimebase_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      hasTimebase_ = buffer.readBoolean();

   }

   @Override
   public void set(Video from)
   {
      hasTimebase_ = from.hasTimebase_;

   }

   public boolean getHasTimebase()
   {
      return hasTimebase_;
   }

   public void setHasTimebase(boolean hasTimebase_)
   {
      this.hasTimebase_ = hasTimebase_;
   }


}