/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/YoType):
<pre>{@code
uint8 DoubleYoVariable=0
uint8 BooleanYoVariable=1
uint8 IntegerYoVariable=2
uint8 LongYoVariable=3
uint8 EnumYoVariable=4
uint8 type 0}</pre>
*/
public class YoType implements ROS2Message<YoType>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::YoType";

   public static final byte DOUBLEYOVARIABLE = 0;
   public static final byte BOOLEANYOVARIABLE = 1;
   public static final byte INTEGERYOVARIABLE = 2;
   public static final byte LONGYOVARIABLE = 3;
   public static final byte ENUMYOVARIABLE = 4;
   private byte type_;

   public YoType()
   {
      type_ = (byte) 0;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // type_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(type_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      type_ = buffer.readByte();

   }

   @Override
   public void set(YoType from)
   {
      type_ = from.type_;

   }

   public byte getType()
   {
      return type_;
   }

   public void setType(byte type_)
   {
      this.type_ = type_;
   }


}