/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package logger_msgs.msg.dds;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (logger_msgs/YoVariableDefinition):
<pre>{@code
string name
string description
logger_msgs/YoType type
uint16 registry
uint16 enumType
bool allowNullValues
bool isParameter
float64 min
float64 max
uint8 loadStatus
}</pre>
*/
public class YoVariableDefinition implements ROS2Message<YoVariableDefinition>
{
   public static final java.lang.String name = "us::ihmc::robotDataLogger::YoVariableDefinition";

   private final StringBuilder name_;
   private final StringBuilder description_;
   private final logger_msgs.msg.dds.YoType type_;
   private short registry_;
   private short enumType_;
   private boolean allowNullValues_;
   private boolean isParameter_;
   private double min_;
   private double max_;
   private byte loadStatus_;

   public YoVariableDefinition()
   {
      name_ = new StringBuilder();
      description_ = new StringBuilder();
      type_ = new logger_msgs.msg.dds.YoType();
      allowNullValues_ = (boolean) false;
      isParameter_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * name_.length()) + 1; // name_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * description_.length()) + 1; // description_
      currentAlignment += type_.calculateSizeBytes(currentAlignment);
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // registry_
      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // enumType_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // allowNullValues_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // isParameter_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // min_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // max_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // loadStatus_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(name_);
      buffer.writeString(description_);
      type_.serialize(buffer);
      buffer.writeShort(registry_);
      buffer.writeShort(enumType_);
      buffer.writeBoolean(allowNullValues_);
      buffer.writeBoolean(isParameter_);
      buffer.writeDouble(min_);
      buffer.writeDouble(max_);
      buffer.writeByte(loadStatus_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(name_);
      buffer.readString(description_);
      type_.deserialize(buffer);
      registry_ = buffer.readShort();
      enumType_ = buffer.readShort();
      allowNullValues_ = buffer.readBoolean();
      isParameter_ = buffer.readBoolean();
      min_ = buffer.readDouble();
      max_ = buffer.readDouble();
      loadStatus_ = buffer.readByte();

   }

   @Override
   public void set(YoVariableDefinition from)
   {
      name_.delete(0, name_.length());
      name_.insert(0, from.name_);
      description_.delete(0, description_.length());
      description_.insert(0, from.description_);
      type_.set(from.type_);
      registry_ = from.registry_;
      enumType_ = from.enumType_;
      allowNullValues_ = from.allowNullValues_;
      isParameter_ = from.isParameter_;
      min_ = from.min_;
      max_ = from.max_;
      loadStatus_ = from.loadStatus_;

   }

   public StringBuilder getName()
   {
      return name_;
   }

   public java.lang.String getNameAsString()
   {
      return name_.toString();
   }

   public void setName(java.lang.String s)
   {
      this.name_.delete(0, this.name_.length());
      this.name_.insert(0, s);
   }

   public StringBuilder getDescription()
   {
      return description_;
   }

   public java.lang.String getDescriptionAsString()
   {
      return description_.toString();
   }

   public void setDescription(java.lang.String s)
   {
      this.description_.delete(0, this.description_.length());
      this.description_.insert(0, s);
   }

   public logger_msgs.msg.dds.YoType getType()
   {
      return type_;
   }

   public short getRegistry()
   {
      return registry_;
   }

   public void setRegistry(short registry_)
   {
      this.registry_ = registry_;
   }

   public short getEnumType()
   {
      return enumType_;
   }

   public void setEnumType(short enumType_)
   {
      this.enumType_ = enumType_;
   }

   public boolean getAllowNullValues()
   {
      return allowNullValues_;
   }

   public void setAllowNullValues(boolean allowNullValues_)
   {
      this.allowNullValues_ = allowNullValues_;
   }

   public boolean getIsParameter()
   {
      return isParameter_;
   }

   public void setIsParameter(boolean isParameter_)
   {
      this.isParameter_ = isParameter_;
   }

   public double getMin()
   {
      return min_;
   }

   public void setMin(double min_)
   {
      this.min_ = min_;
   }

   public double getMax()
   {
      return max_;
   }

   public void setMax(double max_)
   {
      this.max_ = max_;
   }

   public byte getLoadStatus()
   {
      return loadStatus_;
   }

   public void setLoadStatus(byte loadStatus_)
   {
      this.loadStatus_ = loadStatus_;
   }


}