/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package geometry_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (geometry_msgs/Pose):
<pre>{@code
# A representation of pose in free space, composed of position and orientation.
Point position
Quaternion orientation
}</pre>
*/
public class Pose implements ROS2Message<Pose>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::Pose_";

   /**
      A representation of pose in free space, composed of position and orientation.
   */
   private final geometry_msgs.Point position_;
   private final geometry_msgs.Quaternion orientation_;

   public Pose()
   {
      position_ = new geometry_msgs.Point();
      orientation_ = new geometry_msgs.Quaternion();

   }

   public Pose(Pose from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += position_.calculateSizeBytes(currentAlignment);
      currentAlignment += orientation_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      position_.serialize(buffer);
      orientation_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      position_.deserialize(buffer);
      orientation_.deserialize(buffer);

   }

   @Override
   public void set(Pose from)
   {
      position_.set(from.position_);
      orientation_.set(from.orientation_);

   }

   public geometry_msgs.Point getPosition()
   {
      return position_;
   }

   public geometry_msgs.Quaternion getOrientation()
   {
      return orientation_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Pose {");
      builder.append("position_=");
      builder.append(position_);
      builder.append("orientation_=");
      builder.append(orientation_);

      builder.append("}");
      return builder.toString();
   }
}