/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package geometry_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (geometry_msgs/Quaternion):
<pre>{@code
# This represents an orientation in free space in quaternion form.
float64 x
float64 y
float64 z
float64 w
}</pre>
*/
public class Quaternion implements ROS2Message<Quaternion>
{
   public static final java.lang.String name = "geometry_msgs::msg::dds_::Quaternion_";

   /**
      This represents an orientation in free space in quaternion form.
   */
   private double x_;
   private double y_;
   private double z_;
   private double w_;

   public Quaternion()
   {
   }

   public Quaternion(Quaternion from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // x_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // y_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // z_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // w_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(x_);
      buffer.writeDouble(y_);
      buffer.writeDouble(z_);
      buffer.writeDouble(w_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      x_ = buffer.readDouble();
      y_ = buffer.readDouble();
      z_ = buffer.readDouble();
      w_ = buffer.readDouble();

   }

   @Override
   public void set(Quaternion from)
   {
      x_ = from.x_;
      y_ = from.y_;
      z_ = from.z_;
      w_ = from.w_;

   }

   public double getX()
   {
      return x_;
   }

   public void setX(double x_)
   {
      this.x_ = x_;
   }

   public double getY()
   {
      return y_;
   }

   public void setY(double y_)
   {
      this.y_ = y_;
   }

   public double getZ()
   {
      return z_;
   }

   public void setZ(double z_)
   {
      this.z_ = z_;
   }

   public double getW()
   {
      return w_;
   }

   public void setW(double w_)
   {
      this.w_ = w_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Quaternion {");
      builder.append("x_=");
      builder.append(x_);
      builder.append("y_=");
      builder.append(y_);
      builder.append("z_=");
      builder.append(z_);
      builder.append("w_=");
      builder.append(w_);

      builder.append("}");
      return builder.toString();
   }
}